"use strict";

// Turn server/geo_pool.json into the two lookup tables the reveal needs, and emit them as BOTH a
// server constant and a shipped Panorama script. One generator, one ordering: the client renders
// what the worker names by index, so a drift between the two artifacts would silently mislabel
// every reveal. Anything that regenerates one regenerates the other.
//
//   node tools/build_geo_credit_tables.js
//
// ── Why indices at all ──────────────────────────────────────────────────────────────────────
// The attribution line used to be transported as TEXT over the image-dimensions side channel, two
// characters per request: `/api/geocredit?i=0` returned the length, then each further request
// carried two more characters. A 49-character credit ("emanuel alejandro maciel  Mapillary  CC BY
// SA 4.0") is 26 chained round-trips, and showReveal() held the button on "LOADING RESULT…" until
// they finished. That was the entire cause of the long post-guess wait.
//
// None of it was ever dynamic. Every credit string is built from the row's own `provider` and
// `source`, both of which are decided at pool build time. So the strings ship with the mod and the
// wire carries a single index instead - one request, no loop. Same for the country: it rides the
// existing /api/geoinfo reply, which had 3969 codes and was using six.

const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const IN = path.join(root, "server", "geo_pool.json");
const OUT_SERVER = path.join(root, "server", "geo_credit_tables.generated.js");
const OUT_CLIENT = path.join(root, "panorama", "scripts", "mg_geo_credits.generated.js");

// One downlink reply carries two base-63 levels = 3969 distinct values, with h=63 reserved as the
// error sentinel. Both tables must stay under that or the index stops fitting in one request.
const CODE_CAP = 63 * 63;
const REGION_COUNT = 6;

const pool = JSON.parse(fs.readFileSync(IN, "utf8"));
if (!Array.isArray(pool) || !pool.length) {
    console.error("geo_pool.json is empty - run tools/build_geo_pool.js first");
    process.exit(1);
}

// Sorted, not insertion-ordered: a re-harvest that merely reshuffles rows must not renumber every
// index and produce a meaningless diff.
const countries = [];
const pairs = [];
const seenCountry = new Set();
const seenPair = new Set();
for (const row of pool) {
    const name = String(row.country || "");
    if (name && !seenCountry.has(name)) { seenCountry.add(name); countries.push(name); }
    const key = (row.source === 1 ? 1 : 0) + "|" + String(row.provider || "");
    if (!seenPair.has(key)) { seenPair.add(key); pairs.push(key); }
}
countries.sort();
pairs.sort();

// The pool's own field validation lives in build_geo_pool_module.js; this is the narrower check
// that the strings can survive both the packed format (| and \n are separators) and the JS string
// literal they are emitted into.
function checkText(value, what) {
    if (/[|\n"\\]/.test(value)) {
        console.error(`bad ${what} (contains a separator or quote): ${JSON.stringify(value)}`);
        process.exit(1);
    }
}
for (const name of countries) checkText(name, "country");
// A pair key is "source|provider", so the leading digit and its separator are expected; only the
// provider half has to be free of them.
for (const key of pairs) {
    if (!/^[01]\|/.test(key)) {
        console.error(`bad provider pair (no source prefix): ${JSON.stringify(key)}`);
        process.exit(1);
    }
    checkText(key.slice(2), "provider");
}

// The place code packs BOTH the country and its display continent, because a country does not
// imply one: Russia, Turkey, Kazakhstan, Egypt and Indonesia straddle a divide and lib/country.js
// resolves them per point. Layout: 0..5 = region only, 6 + countryIndex*6 + continent.
const topPlace = REGION_COUNT + countries.length * REGION_COUNT - 1;
if (topPlace >= CODE_CAP) {
    console.error(`place codes exceed one reply: top code ${topPlace}`);
    process.exit(1);
}
if (pairs.length >= CODE_CAP) {
    console.error(`credit codes exceed one reply: ${pairs.length}`);
    process.exit(1);
}

const SOURCES = ["Panoramax", "Mapillary"];

// The credit line the reveal renders. Assembled on the CLIENT from these tables, so the exact
// wording lives in one place and costs no bandwidth. CC BY-SA 4.0 requires naming the creator and
// the licence; both providers serve their panoramas under it.
const creditLines = pairs.map((key) => {
    const cut = key.indexOf("|");
    const source = SOURCES[Number(key.slice(0, cut)) === 1 ? 1 : 0];
    const provider = key.slice(cut + 1);
    return provider + " · " + source + " · CC BY-SA 4.0";
});

const stamp = "GENERATED by tools/build_geo_credit_tables.js from server/geo_pool.json - DO NOT EDIT.";

// Server side: the worker is one concatenated script with no filesystem, so the tables arrive as
// source. It only ever needs the INDEX of a row, so it gets the keys, not the rendered text.
const serverOut =
    "/* " + stamp + " */\n" +
    "/* Reveal lookup tables. GEO_COUNTRY_NAMES is indexed by a place code (see geoPlaceCode);\n" +
    "   GEO_CREDIT_KEYS is \"source|provider\", matching the pool's own rows. Both orders MUST\n" +
    "   match panorama/scripts/mg_geo_credits.generated.js, which renders what these name. */\n" +
    "const GEO_COUNTRY_NAMES = " + JSON.stringify(countries) + ";\n" +
    "const GEO_CREDIT_KEYS = " + JSON.stringify(pairs) + ";\n";

// Client side: never needs the keys, only the rendered strings, in the same order.
const clientOut =
    "/* " + stamp + " */\n" +
    "/* global $ */\n" +
    "(function () {\n" +
    "    \"use strict\";\n" +
    "    var MG = $.MG = $.MG || {};\n" +
    "    // Indexed by the place code /api/geoinfo returns: 0..5 = region only, and at 6 and above\n" +
    "    // (place - 6) packs country * 6 + continent (see MG.Api.geoPlace).\n" +
    "    MG.GeoCountries = " + JSON.stringify(countries) + ";\n" +
    "    // Indexed by the single code /api/geocredit returns. Was transported two characters\n" +
    "    // per request; shipping it costs ~" + Math.round(creditLines.join("").length / 1024) +
    " KiB and saves up to 26 round-trips per round.\n" +
    "    MG.GeoCredits = " + JSON.stringify(creditLines) + ";\n" +
    "})();\n";

fs.writeFileSync(OUT_SERVER, serverOut, "utf8");
fs.writeFileSync(OUT_CLIENT, clientOut, "utf8");
console.log("wrote " + path.relative(root, OUT_SERVER) +
    " (" + (serverOut.length / 1024).toFixed(1) + " KiB)");
console.log("wrote " + path.relative(root, OUT_CLIENT) +
    " (" + (clientOut.length / 1024).toFixed(1) + " KiB)");
console.log("  " + countries.length + " countries (place codes 6.." + topPlace + "), " +
    pairs.length + " credit codes · cap " + CODE_CAP);
