"use strict";

// Turn server/geo_pool.json into server/geo_pool.generated.js, the form the worker can actually
// load. The worker is a single concatenated script (see tools/build_worker.js) with no filesystem
// and no `require`, so the pool has to arrive as source.
//
//   node tools/build_geo_pool_module.js
//
// The JSON stays the builder's output and the reviewable artifact: it diffs per location, while
// this generated module is one packed line. Rows are packed as
//
//   source|id|lat|lon|region|provider
//
// rather than JSON objects, because 2400 repetitions of the same six keys cost ~120 KiB of pure
// punctuation in a file that ships inside every deploy. Provider names are already restricted to
// [ A-Za-z0-9.] by the builder's safeName(), so neither separator can appear inside a field.

const fs = require("fs");
const path = require("path");

const root = path.join(__dirname, "..");
const IN = path.join(root, "server", "geo_pool.json");
const OUT = path.join(root, "server", "geo_pool.generated.js");

const REGION_COUNT = 6;

const pool = JSON.parse(fs.readFileSync(IN, "utf8"));
if (!Array.isArray(pool) || !pool.length) {
    console.error("geo_pool.json is empty - run tools/build_geo_pool.js first");
    process.exit(1);
}

const lines = [];
for (const row of pool) {
    const source = row.source === 1 ? 1 : 0;
    const id = String(row.id);
    const lat = Number(row.lat), lon = Number(row.lon);
    const region = Number(row.region);
    // Validate here rather than in the worker: a malformed row is a build-time bug, and the
    // worker should not carry parsing defences for data this file guarantees.
    const idOk = source === 1 ? /^[0-9]{5,25}$/.test(id) : /^[0-9a-f-]{36}$/i.test(id);
    if (!idOk || !Number.isFinite(lat) || !Number.isFinite(lon) ||
        lat < -90 || lat > 90 || lon < -180 || lon > 180 ||
        !Number.isInteger(region) || region < 0 || region >= REGION_COUNT) {
        console.error("bad pool row: " + JSON.stringify(row));
        process.exit(1);
    }
    const provider = String(row.provider || "").replace(/[^ A-Za-z0-9.]/g, "").trim();
    lines.push(source + "|" + id + "|" + lat.toFixed(6) + "|" + lon.toFixed(6) +
        "|" + region + "|" + provider);
}

const packed = lines.join("\n");
if (packed.indexOf("\\") !== -1 || packed.indexOf("\"") !== -1) {
    console.error("packed pool contains a character that would need escaping");
    process.exit(1);
}

const out =
    "/* GENERATED by tools/build_geo_pool_module.js from server/geo_pool.json - DO NOT EDIT. */\n" +
    "/* " + pool.length + " prebuilt 360-degree panorama locations: source|id|lat|lon|region|provider\n" +
    "   source 0 = Panoramax, 1 = Mapillary. Starting a lobby picks from this list and makes\n" +
    "   ZERO catalog requests. Refresh with tools/build_geo_pool.js, then rerun this. */\n" +
    "const GEO_POOL_PACKED = \"" + packed.replace(/\n/g, "\\n") + "\";\n";

fs.writeFileSync(OUT, out, "utf8");
console.log("wrote " + path.relative(root, OUT) + " (" + (out.length / 1024).toFixed(1) +
    " KiB, " + pool.length + " locations)");
