"use strict";

// Generates the offline Panorama dictionary from the two MIT-licensed word lists in
// ayaanhossain/weldor. Normal game builds use the checked-in generated file and never need
// network access. Run without arguments to refresh from the pinned GitHub revision, or pass
// --source-dir <weldor checkout> while reviewing a newer upstream revision.

const fs = require("fs");
const path = require("path");

const SOURCE_COMMIT = "bb26f1a804e8d4a50f0844f27334bc7f29cfe742";
const SOURCE_BASE = "https://raw.githubusercontent.com/ayaanhossain/weldor/" +
    SOURCE_COMMIT + "/weldor/wordbase/";
const OUTPUT = path.join(__dirname, "..", "panorama", "scripts",
    "mg_wordle_words.generated.js");

function sourceDirectory() {
    const index = process.argv.indexOf("--source-dir");
    if (index < 0) return "";
    if (!process.argv[index + 1]) throw new Error("--source-dir requires a path");
    return path.resolve(process.argv[index + 1]);
}

async function readSource(name, directory) {
    if (directory) {
        return fs.readFileSync(path.join(directory, "weldor", "wordbase", name), "utf8");
    }
    const response = await fetch(SOURCE_BASE + name);
    if (!response.ok) throw new Error("Unable to download " + name + ": HTTP " + response.status);
    return response.text();
}

function parseWords(text, label) {
    const words = text.trim().split(/\s+/).map((word) => {
        return word.toUpperCase();
    });
    const seen = {};
    for (let i = 0; i < words.length; i++) {
        const word = words[i];
        if (!/^[A-Z]{5}$/.test(word)) throw new Error(label + " contains invalid word: " + word);
        if (seen[word]) throw new Error(label + " contains duplicate word: " + word);
        seen[word] = true;
    }
    return words;
}

function wordExpression(words) {
    const lines = [];
    for (let i = 0; i < words.length; i += 14) {
        const chunk = words.slice(i, i + 14).join(" ");
        lines.push("        \"" + chunk + (i + 14 < words.length ? " \" +" : "\""));
    }
    return "(\n" + lines.join("\n") + "\n    ).split(\" \")";
}

function render(answers, guesses) {
    return `"use strict";

/*
 * GENERATED by tools/build_wordle_words.js from:
 * https://github.com/ayaanhossain/weldor/tree/${SOURCE_COMMIT}/weldor/wordbase
 *
 * MIT License
 *
 * Copyright (c) 2022 Ayaan Hossain
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
(function () {
    var MG = $.MG = $.MG || {};
    if (MG.WordleWords) return;
    MG.WordleWords = {
        answers: ${wordExpression(answers)},
        guesses: ${wordExpression(guesses)},
        sourceCommit: "${SOURCE_COMMIT}"
    };
})();
`;
}

async function main() {
    const directory = sourceDirectory();
    const answers = parseWords(await readSource("index.txt", directory), "answers");
    const guesses = parseWords(await readSource("shell.txt", directory), "guesses");
    const answerSet = {};
    for (let i = 0; i < answers.length; i++) answerSet[answers[i]] = true;
    for (let i = 0; i < guesses.length; i++) {
        if (answerSet[guesses[i]]) {
            throw new Error("answer/guess lists overlap at " + guesses[i]);
        }
    }
    fs.writeFileSync(OUTPUT, render(answers, guesses), "utf8");
    console.log("Wrote " + path.relative(process.cwd(), OUTPUT) + " with " +
        answers.length + " answers and " + guesses.length + " additional guesses.");
}

main().catch((error) => {
    console.error(error.stack || error);
    process.exitCode = 1;
});
