/**
 * Deadlock Minigames relay — Cloudflare Worker CORE (authored source).
 *
 * ⚠ DO NOT DEPLOY THIS FILE DIRECTLY. The deploy artifact is `server/worker.js`,
 * generated by `node tools/build_worker.js`, which prepends the SHARED rule engines
 * (panorama/scripts/rules/*.js) so the server validates moves with byte-for-byte the
 * same code the client predicts with. Edit THIS file, then rebuild. See server/README.md.
 *
 * Panorama UI has no fetch / no AsyncWebRequest / no websockets. The ONLY channel
 * back to the client is the intrinsic pixel size of an <Image>: the client sets an
 * image src and reads actuallayoutwidth / actuallayoutheight. So every response here
 * is a tiny PNG whose (width, height) ENCODE two integers.
 *
 * Sending data TO the server is unlimited (URL query params). Only the RESPONSE is
 * squeezed into (width, height). This asymmetry is why the SEAT TOKEN (identity) can
 * flow up freely in the query while the downlink stays two small ints.
 *
 * Transport is strongly consistent because all state lives in ONE Durable Object
 * instance ("hub"). No KV eventual-consistency lag between the two players — ideal for
 * holding the authoritative board copy.
 *
 * DOWNLINK ENCODING (2026-07-20): every DATA response carries a small "level" per
 * dimension, dim = level*9 + 15 (see the d() encoder near the bottom). This survives
 * UI-scaled displays where the old dim=int+1 died (value 1 rendered as 2). Safe range is
 * levels 0..63 per dimension. The (w,h) pairs below are those LEVELS (what the client
 * decodes back), NOT raw pixels. Only /api/probe stays literal pixels (600,1000) — it's
 * the calibration reference. Proven 720p–8K by tools/mg_simulate_resolutions.js.
 *
 * Routes (all GET, all return a PNG; pass &rnd=<random> to defeat engine caching):
 *   /api/probe                                    -> (600,1000) LITERAL px      swap + scale calibration
 *   /api/ping                                     -> (1,1)                       UI tester route
 *   /api/create?game=G&tok=T                      -> dCode(code, host=false)     new PRIVATE lobby, host = seat 0
 *   /api/quick?game=G&tok=T                        -> dCode(code, JOINER|HOST)   role is the code BAND, not +100
 *   /api/cancel?code=C                            -> (1,1)                       drop a still-waiting lobby
 *   /api/join?code=C&tok=T                         -> (G, tcIndex+1) ok · (20,1) missing · (21,1) full
 *   /api/status?code=C                            -> (players, game+1) · (9,1) gone
 *   /api/move?code=C&from=F&to=T&end=E&tok=T       -> (1,1) ok · (9,1) not-your-turn · (9,2) illegal · (9,3) bad-token · (9,9) gone
 *   /api/poll?code=C&since=S                       -> (from, to) RAW squares · (1,1) nothing new
 *   /api/reset?code=C&game=G&tok=T                 -> (1,1)
 *   /api/clocks?code=C&seat=S                      -> (30+sec>>6, sec&63) one seat · (9,9) no lobby · (9,8) untimed
 *
 * CODES are rebased to 0..1023 (was 4-digit 1000..9999) so a code half fits a level. dCode()
 * splits code = hi<<6 | lo: width = BAND + hi (joiner/create band 24, host band 40), height =
 * lo. The band both stays clear of every sentinel (1 ok · 9 err · 20/21/22 formation) AND
 * encodes the host/joiner role, so the old fragile +100 role flag is gone. validCode()
 * canonicalises the client's decimal code to the int storage key.
 *
 * POLL sends the move as RAW squares (from,to), no +1, no +100. The turn-hand-off flag `end`
 * is NOT transmitted — from+to+end is 13 bits > the 12 the codec allows — it is DERIVED on the
 * client by replaying the SAME shared rules engine on the SAME board (a mid-chain capture with
 * more jumps keeps the turn; else it hands off). The server stays authoritative on move
 * LEGALITY; end is pure segmentation. from != to for a real move, so (1,1) is still "nothing".
 *
 * CLOCKS are per-seat now (was both banks in one image): a bank is 0..600 = 10 bits and needs
 * BOTH dimensions (hi=sec>>6 on width band 30..39, lo=sec&63 on height). The caller passes
 * &seat=0|1 and polls both ~1/s. Both clients read the SAME server clock, so flag-fall (a
 * seat's bank hitting 0 = that seat loses) is server-decided with no drift. tc (60/180/300/600 s)
 * is chosen at create (create?tc=SEC), forced to 300 for a quick match, and carried to the
 * joiner as a small INDEX in the /api/join height (tcIndex, not raw seconds which overflow a
 * level). Untimed games (TTT/Durak/C4, tc=0) get (9,8) and never poll clocks.
 *
 * Move rejection codes all fit the 2-int downlink (width 9 + a small height discriminator):
 *   (9,1) not your turn · (9,2) illegal move · (9,3) bad/foreign token · (9,9) no lobby.
 */

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (!url.pathname.startsWith("/api/")) {
      return new Response("Deadlock Minigames relay OK", { status: 200 });
    }
    // All game state lives in a single strongly-consistent Durable Object.
    const id = env.HUB.idFromName("hub");
    const stub = env.HUB.get(id);
    return stub.fetch(request);
  },
};

export class Hub {
  constructor(state) {
    this.state = state;
    this.storage = state.storage;
    // In-memory per-IP sliding window for the lobby-FORMATION routes (create/join family).
    // Lives on the single Durable Object instance, so every request sees the same counters
    // (no KV lag). Keyed by CF-Connecting-IP: legit players sit on distinct IPs and never
    // approach the cap, while a brute-forcer sweeping the 4-digit code space or flooding
    // `create` is one IP and gets throttled. A null IP (local/tests) is exempt (fails open),
    // and the HOT read/poll loop is DELIBERATELY never throttled — a (9,x) sentinel there
    // would be misread by the poll decoder as a real move. Bounded to RL_MAX_IPS entries so
    // the map itself can't be used to exhaust memory.
    this.rl = new Map();          // ip -> array of recent request timestamps (ms)
  }

  // Sliding-window rate check for one IP. Returns true if this request is ALLOWED. A null/
  // empty IP is always allowed (local dev + the test harness send no CF-Connecting-IP). Prunes
  // timestamps older than the window on each call, and evicts the oldest IP once the map is
  // full so a spoofed-IP flood can't grow it without bound.
  rateOk(ip) {
    if (!ip) return true;
    const now = Date.now();
    let hits = this.rl.get(ip);
    if (!hits) {
      if (this.rl.size >= RL_MAX_IPS) { const first = this.rl.keys().next().value; if (first !== undefined) this.rl.delete(first); }
      hits = [];
      this.rl.set(ip, hits);
    }
    // Drop timestamps outside the window (in place, cheap for small arrays).
    let k = 0;
    for (let i = 0; i < hits.length; i++) if (now - hits[i] < RL_WINDOW_MS) hits[k++] = hits[i];
    hits.length = k;
    if (hits.length >= RL_MAX_HITS) return false;
    hits.push(now);
    return true;
  }

  async fetch(request) {
    const url = new URL(request.url);
    // Panorama's <Image> loader only fetches URLs that look like an image, so the
    // client appends ".png" to every route. Strip it here before routing.
    const p = url.pathname.replace(/\.png$/, "");
    const q = url.searchParams;
    // Normalise `code` to a canonical 4-digit integer string, or "" if it isn't one. All
    // real lobby codes are 1000..9999 (freshCode), so anything else (unicode, "1e3", a
    // giant string) can never name a live lobby — reject it here so it can't create junk
    // "l:<garbage>" keys or match via loose string coercion. "" makes every `code ? …`
    // guard below fall straight to the missing/gone branch.
    const code = validCode(q.get("code"));

    // Rate-limit the formation + existence-probe routes by client IP (Cloudflare sets
    // CF-Connecting-IP; absent locally / in tests → fails open). (9,4) is a dedicated
    // "slow down" marker the throttled client methods surface as a friendly retry, and
    // it can never be confused with a real reply on these routes.
    if (THROTTLED_ROUTES[p] && !this.rateOk(request.headers.get("CF-Connecting-IP"))) {
      return d(9, 4);
    }

    try {
      if (p === "/api/probe") return png(600, 1000);
      if (p === "/api/ping") return d(1, 1);

      if (p === "/api/create") {
        await this.maybeSweep();
        const game = clampInt(q.get("game"), 1, 1, 9);
        if (!SUPPORTED_GAMES[game]) return d(9, 6);      // unsupported game id (6..9 have no engine)

        if (!validTok(q.get("tok"))) return d(9, 3);     // reject empty/garbage seat token
        const newCode = await this.freshCode();

        const tc = clockSecFor(game, q.get("tc"));         // 0 unless chess/checkers with a bank
        const lobby = {
          game, players: 1, moves: [], pub: 0, t: nowSeq(),
          seats: [{ tok: q.get("tok") || "" }, null], // seat 0 = host = white/X/+1, moves first
          turn: 0,                                     // seat index whose turn it is
          tc: tc,                                      // per-seat bank in SECONDS (0 = no clock)
          state: initState(game)                       // authoritative board/state
        };
        initClock(lobby);
        await this.storage.put("l:" + newCode, lobby);
        // Code rides the level-quantised downlink in the joiner/create band (see dCode).
        return dCode(newCode, false);
      }

      if (p === "/api/quick") {
        await this.maybeSweep();
        const game = clampInt(q.get("game"), 1, 1, 9);
        if (!SUPPORTED_GAMES[game]) return d(9, 6);      // unsupported game id (6..9 have no engine)
        if (!validTok(q.get("tok"))) return d(9, 3);     // reject empty/garbage seat token

        // TIME-CONTROL matchmaking (chess/checkers only; other games have no bank). The picker
        // sends tc = concrete SECONDS (60/180/300/600) or the literal "any". Searchers pool by
        // (game, tc-bucket) so a 1-min seeker never gets force-matched into a 10-min waiter:
        //   • concrete T  → join a same-T waiter, else an "any" waiter (which then adopts T),
        //                   else host a T lobby.
        //   • "any"       → join ANY waiter (adopt its bank; if that waiter is itself "any",
        //                   the game resolves to 5 min), else host an "any" lobby.
        // Non-clock games ignore tc entirely and share one bucket ("0"). Single-quick queues use
        // the prefix pubq:q:<game>:<bucket> so they never collide with mquick's pubq:<game>.
        const clockGame = !!CLOCK_GAMES[game];
        const rawTc = q.get("tc");
        const wantAny = clockGame && rawTc === "any";
        const wantTc = clockGame && !wantAny ? clockSecFor(game, rawTc) : 0;  // concrete secs, else 0
        // The bank this seeker will impose once paired: a concrete pick fixes to itself; "Any"
        // resolves to 5 min against an unbanked/undecided host. (When joining a single-quick host
        // that already holds a concrete bank, that host's bank stands instead — see below.)
        const seekerTc = clockGame ? (wantAny ? 300 : wantTc) : 0;
        // Candidate queues to try joining, in order:
        //   • single-quick tc buckets (pubq:q:<game>:<bucket>) — a concrete seeker also accepts an
        //     "any" host; an "any" seeker sweeps every bucket.
        //   • the shared mquick queue (pubq:<game>) — an undecided multi-select host (game 0) whose
        //     candidate set includes this game; finalizeJoin fixes the game for it.
        // Each entry is [storageKey, isMquickQueue].
        const buckets = !clockGame ? ["0"]
          : wantAny ? ["60", "180", "300", "600", "any"]
          : [String(wantTc), "any"];
        const qkey = (b) => "pubq:q:" + game + ":" + b;
        const queues = buckets.map((b) => [qkey(b), false]);
        queues.push(["pubq:" + game, true]);   // mquick multi-hosts live here (undecided game 0)

        for (let i = 0; i < queues.length; i++) {
          const waitCode = await this.storage.get(queues[i][0]);
          if (!waitCode) continue;
          const w = await this.storage.get("l:" + waitCode);
          const isMulti = w && w.game === 0 && w.games && w.games.indexOf(game) >= 0;
          if (w && w.pub && w.players < 2 && (w.game === game || isMulti)) {
            // Resolve the bank now that both seats are known:
            //   • single-quick host with a concrete bank (w.tc>0, not qtcAny) → that bank stands.
            //   • single-quick "any" host (qtcAny) or an mquick multi-host (no bank) → the seeker
            //     imposes seekerTc (its own concrete T, or 5 min if it too asked for "Any").
            if (!clockGame) w.tc = 0;
            else if (w.qtcAny || isMulti || !w.tc) { w.tc = seekerTc; delete w.qtcAny; }
            // else the host's concrete w.tc stands and the joiner plays at it.
            await this.finalizeJoin(waitCode, w, q.get("tok"), game);
            return dCode(Number(waitCode), false); // JOINER (black)
          }
          // stale/closed slot — try the next queue, then fall through to hosting.
        }

        // No match: host a fresh public lobby in OUR bucket and wait.
        const hostBucket = !clockGame ? "0" : wantAny ? "any" : String(wantTc);
        const newCode = await this.freshCode();
        const lobby = {
          game, players: 1, moves: [], pub: 1, t: nowSeq(),
          seats: [{ tok: q.get("tok") || "" }, null], // host takes seat 0 (white/X/+1)
          turn: 0,
          tc: clockGame && !wantAny ? wantTc : 0,      // concrete bank, or 0 while an "any" host is unresolved
          qtcAny: clockGame && wantAny ? 1 : 0,        // unresolved "any" host — its bank is fixed at join
          qk: qkey(hostBucket),                        // the queue slot this lobby holds (for clearQueuesFor)
          state: initState(game)
        };
        initClock(lobby);
        await this.storage.put("l:" + newCode, lobby);
        await this.storage.put(qkey(hostBucket), newCode);
        // HOST (white): +100 on the width flags the role without a fragile extra value.
        return dCode(newCode, true);
      }

      // Multi-select quick match. The caller sends a SET of games it will accept
      // (games=1,2,4,5 — the uplink is unlimited, so the whole set rides up freely).
      // A joiner takes any waiting host whose game (or candidate set) intersects ours,
      // FIXING the lobby to the matched game. With no match, we host ONE undecided lobby
      // (game 0) registered in EVERY selected per-game queue; the first joiner to pick one
      // of them fixes the game. Both sides learn the chosen game from /api/status (its
      // height carries game+1), so no extra downlink value is needed.
      if (p === "/api/mquick") {
        await this.maybeSweep();
        if (!validTok(q.get("tok"))) return d(9, 3);     // reject empty/garbage seat token
        const set = parseGameSet(q.get("games"));
        if (set.length === 0) return d(9, 6);            // no valid multi-capable game ids
        for (let i = 0; i < set.length; i++) {
          const g = set[i];
          const waitCode = await this.storage.get("pubq:" + g);
          if (!waitCode) continue;
          const w = await this.storage.get("l:" + waitCode);
          if (w && w.pub && w.players < 2 &&
              (w.game === g || (w.game === 0 && w.games && w.games.indexOf(g) >= 0))) {
            await this.finalizeJoin(waitCode, w, q.get("tok"), g);
            return dCode(Number(waitCode), false); // JOINER
          }
        }
        const newCode = await this.freshCode();
        const lobby = {
          game: 0, games: set, players: 1, moves: [], pub: 1, t: nowSeq(),
          seats: [{ tok: q.get("tok") || "" }, null],      // host takes seat 0
          turn: 0,
          state: null                                      // fixed once a joiner picks a game
        };
        await this.storage.put("l:" + newCode, lobby);
        for (let i = 0; i < set.length; i++) await this.storage.put("pubq:" + set[i], newCode);
        // HOST: +100 on the width flags the role, exactly like /api/quick.
        return dCode(newCode, true);
      }

      if (p === "/api/cancel") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        // Only a SEATED player (valid token) may cancel, and only while the lobby is still
        // waiting for the second player. Never let a 4-digit code-guesser nuke an active match.
        if (lobby && seatOf(lobby, q.get("tok")) >= 0 && lobby.players < 2) {
          await this.storage.delete("l:" + code);
          await this.clearQueuesFor(lobby, code); // clear every per-game queue this lobby holds
        }
        return d(1, 1);
      }

      // ── leave a game already in progress ──────────────────────────────────────
      // `cancel` only fires while a lobby is still waiting (players < 2). Once a match is live,
      // the "Leave" button hits THIS route so the opponent learns immediately instead of relying
      // on the 30-min idle sweep. A valid seat token is the anchor of trust — a 4-digit
      // code-guesser holds no seat token, so it can never nuke someone else's active match.
      //   • Pair games (board games, or any table down to its last two present players): the lobby
      //     is deleted, so the survivor's next poll/dlog/plog — and any action — returns (9,9) and
      //     the client shows "Opponent left." (they win a decided game).
      //   • 3–4-seat durak/poker with ≥3 present: the seat is folded out via durakLeave/pokerLeave,
      //     which appends a LEFT event (+ DRAW/ROLES or board/WIN) to the public log so the table
      //     plays on without the leaver. The game only ends here if it drops to one player.
      if (p === "/api/leave") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return d(1, 1);                       // already gone — nothing to do
        const seat = seatOf(lobby, q.get("tok"));
        if (seat < 0) return d(1, 1);                     // not a seated player: ignore, don't leak
        lobby.left = lobby.left || [];
        if (lobby.left.indexOf(seat) < 0) lobby.left.push(seat);
        const started = !!(lobby.state && lobby.state.started);
        const present = lobby.players - lobby.left.length;  // still-seated players after this leave
        const isMultiSeat = !!lobby.cap && (lobby.game === 3 || lobby.game === 6);
        if (started && isMultiSeat && present >= 2) {
          // Table plays on without the leaver: fold them out and log it.
          if (lobby.game === 3) durakLeave(lobby, seat);
          else pokerLeave(lobby, seat);
          lobby.t = nowSeq();
          await this.storage.put("l:" + code, lobby);
          return d(1, 1);
        }
        // Pair game, pre-start lobby, or the table just dropped to one player → tear it down.
        await this.storage.delete("l:" + code);
        await this.clearQueuesFor(lobby, code);
        return d(1, 1);
      }


      if (p === "/api/join") {
        if (!validTok(q.get("tok"))) return d(9, 3); // reject empty/garbage seat token
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return d(20, 1);             // missing
        // Game-type guard (H2): the generic 2-seat join hard-sets players=2/seats[1], which would
        // CORRUPT an N-seat poker/durak lobby (those carry `cap` and grow via seats.push through
        // pjoin/djoin). A poker lobby (game 6) is never joinable here either. Refuse both so a
        // guessed code can't clobber a multi-seat table — the client already routes them to
        // pjoin/djoin, so a legitimate joiner never hits this path.
        if (lobby.cap || lobby.game === 6) return d(20, 1); // not a generic 2-seat lobby → "missing"
        if (lobby.players >= 2) return d(21, 1); // full

        lobby.players = 2;
        lobby.seats = lobby.seats || [null, null];
        lobby.seats[1] = { tok: q.get("tok") || "" }; // joiner takes seat 1
        initClock(lobby);                          // arm the bank now that both seats are present
        await this.storage.put("l:" + code, lobby);
        // height carries the time-control INDEX+1 (0..4 → 1..5) so the joiner learns the host's
        // chosen bank without picking it. Index (not raw seconds) keeps it inside one level dim.
        // tc=0 → index 0 → height 1 (no clock), a plain "which game" reply.
        return d(lobby.game, tcIndex(lobby.tc || 0) + 1); // w: game (1..9) · h: tc-index + 1
      }

      if (p === "/api/status") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return d(9, 1);              // gone
        // height carries the chosen game + 1 (1 while an mquick lobby is still undecided,
        // game=0). A multi-select HOST reads it to learn which game a joiner picked; the
        // single-game callers ignore it (they already know their game). Never (9,x).
        return d(lobby.players, (lobby.game || 0) + 1); // w: 1|2 players · h: game+1
      }

      if (p === "/api/move") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return d(9, 9);              // no lobby
        if (lobby.players < 2) return d(9, 1);   // can't move before the opponent has joined
        const seat = seatOf(lobby, q.get("tok"));
        if (seat < 0) return d(9, 3);            // bad / foreign token — caller isn't a seat here
        const from = clampInt(q.get("from"), 0, 0, 63);
        const to = clampInt(q.get("to"), 0, 0, 63);
        const end = clampInt(q.get("end"), 0, 0, 1);
        // Authoritative validation: the server owns the board, enforces whose turn it is,
        // and rejects any illegal move with a (9,x) code. The stored `end` is the one the
        // SERVER computes (never the client's), so a cheat can't forge the turn hand-off.
        // A seat that has already flagged (bank ran out) is out of moves — the game is over on
        // time and the server refuses further play from either side.
        if (clockCheckFlag(lobby) >= 0) { await this.storage.put("l:" + code, lobby); return d(9, 2); }
        const v = validateMove(lobby, seat, from, to, end);
        if (!v.ok) return d(9, v.code);          // (9,1) not your turn · (9,2) illegal
        // Hard ceiling on the move log (poll?since indexes it directly, so it can't be
        // truncated — we refuse to grow it past a size no real game reaches). A legit chess/
        // checkers game is well under 600 plies; MOVE_CAP is pure-abuse territory (two colluding
        // seats shuffling a piece to bloat the DO's storage). Reject as illegal past the cap.
        if (lobby.moves.length >= MOVE_CAP) return d(9, 2);
        lobby.moves.push(v.move);
        lobby.t = nowSeq();                        // keep-alive: TTL is measured from last activity
        // Clock accounting: bill the elapsed time to the seat that just moved, and (only when
        // the move ENDS the turn) start the opponent's clock. Mid-chain hops (checkers multi-
        // jump, v.move.e === 0) keep the SAME clock running — the turn hasn't handed off yet.
        // validateMove already advanced lobby.turn on a hand-off, so it names the next seat.
        clockCharge(lobby, v.move.e === 1, lobby.turn);
        await this.storage.put("l:" + code, lobby);
        return d(1, 1);                          // accepted
      }


      if (p === "/api/poll") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return d(9, 9);              // 9x9 signals lobby destroyed / opponent left
        const since = clampInt(q.get("since"), 0, 0, 100000);
        const mv = lobby.moves[since]; // 0-based; this move is seq = since+1
        if (!mv) return d(1, 1);                 // nothing new (from==to can't be a real move)
        // width = from square, height = to square, both RAW 0..63. The turn-hand-off
        // flag `end` is NO LONGER sent: it fit neither dimension under the level codec
        // (from+to+end = 13 bits > 12), and it is derivable — the client applies the SAME
        // shared rules engine to the SAME board and recomputes it bit-for-bit (a mid-chain
        // capture with more jumps available keeps the turn; else it hands off). The server
        // stays authoritative on move LEGALITY; `end` is pure segmentation, safe to derive.
        // from != to for every real move, so a genuine reply can never read as (1,1).
        return d(mv.f, mv.t);
      }

      // Authoritative clocks. Returns ONE seat's remaining SECONDS per read (the caller
      // passes &seat=0|1 and polls both ~1/s). Splitting per-seat is forced by the level
      // codec: a bank is 0..600 = 10 bits, which needs BOTH dimensions (hi=sec>>6 on the
      // width, lo=sec&63 on the height), leaving no room to pack two banks in one image.
      //   -> (CLK_BASE+hi, lo)   remaining seconds for the asked seat (sec = hi*64 + lo)
      //   -> (9, 9)              lobby gone
      //   -> (9, 8)              lobby is UNTIMED (no bank configured)
      // Sentinels use width 9 (never a real clock: CLK_BASE=30 puts a real reading at width
      // 30..39), so they can't be misread as a time the way the old height>=900 trick risked.
      // Both clients read the SAME server clock, so they can't disagree on the time or on who
      // flagged: a seat's bank reaching 0 IS the flag-fall signal (that seat loses).
      if (p === "/api/clocks") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return d(9, 9);              // gone
        if (!lobby.clkMs) return d(9, 8);        // untimed game → no clocks
        // Persist a freshly-detected flag so the outcome sticks for later polls / moves.
        if (clockCheckFlag(lobby) >= 0) await this.storage.put("l:" + code, lobby);
        const seat = clampInt(q.get("seat"), 0, 0, 1);
        const s = Math.min(600, Math.max(0, clockSec(lobby, seat)));
        return d(CLK_BASE + ((s >> 6) & 15), s & 63);   // width band 30..39, height 0..63
      }

      if (p === "/api/reset") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return d(9, 9);
        if (seatOf(lobby, q.get("tok")) < 0) return d(9, 3); // only a seated player may reset
        // Rematch = same game, fresh state. The game TYPE is fixed at create time and can
        // never be switched mid-lobby (that would desync / void the opponent's board).
        lobby.moves = [];
        lobby.turn = 0;
        lobby.state = initState(lobby.game);
        initClock(lobby);                          // fresh banks for the rematch
        lobby.t = nowSeq();
        await this.storage.put("l:" + code, lobby);
        return d(1, 1);
      }

      // Rematch handshake. Both seats poll this from the game-over screen; when BOTH have
      // asked, the server performs the same reset as /api/reset, bumps `gen`, clears the
      // ready flags, and reports (2, gen+1). Until then it reports (1, gen+1) = "waiting".
      //   -> (1, gen+1) I'm marked, waiting for the opponent
      //   -> (2, gen+1) both ready: state was reset THIS call, restart now
      //   -> (9,3) bad/foreign token · (9,9) no lobby
      // The caller passes &gen=<its current generation>. We only ARM a seat's flag when that
      // matches the lobby's live `gen`; a stale poll from BEFORE a restart (old gen) can't
      // re-arm the next rematch, it just reads the bumped gen and the client restarts. This is
      // what stops the flag "sticking" across consecutive rematches (no extra clear round-trip).
      if (p === "/api/rematch") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return d(9, 9);
        const seat = seatOf(lobby, q.get("tok"));
        if (seat < 0) return d(9, 3);
        lobby.gen = (lobby.gen || 0) % 63;         // normalise a legacy/persisted gen into 6 bits
        if (lobby.players < 2) return d(1, lobby.gen + 1); // opponent already left/never joined
        lobby.rm = lobby.rm || [false, false];
        const callerGen = clampInt(q.get("gen"), 0, 0, 100000);
        if (callerGen === lobby.gen) lobby.rm[seat] = true; // only arm against the live generation
        lobby.t = nowSeq();                                 // keep-alive
        if (lobby.rm[0] && lobby.rm[1]) {
          lobby.moves = [];
          lobby.turn = 0;
          lobby.state = initState(lobby.game);
          initClock(lobby);                        // fresh banks for the rematch
          // Wrap the generation into 6 bits so gen+1 stays a valid level (<=63) on the
          // downlink. gen is only used for equality / "did a restart happen" detection, and
          // 63 rematches can't elapse between two of a client's polls, so wrapping is safe.
          lobby.gen = (lobby.gen + 1) % 63;
          lobby.rm = [false, false];
          await this.storage.put("l:" + code, lobby);
          return d(2, lobby.gen + 1);                     // both ready: reset done, gen bumped
        }
        await this.storage.put("l:" + code, lobby);
        return d(1, lobby.gen + 1);                       // waiting for the opponent
      }


      // ── Durak (authoritative dealer, 2 players) ────────────────────────────
      // Separate route set from the 2-int move/poll games: the worker OWNS the deck,
      // hands and seed, deals PRIVATELY per seat via /api/ddraw, and relays PUBLIC events
      // via an indexed /api/dlog. Clients rebuild table/trump/turn/roles/counts from the
      // public log and learn only their OWN card identities privately. All actions require
      // a seat token (tok → seat), which also gates ddraw so a cheat can't read a foreign
      // seat's private cards. Only 2 players are wired for now (3–4 seating is deferred).
      if (p === "/api/room") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return d(9, 1);                        // gone
        const started = lobby.state && lobby.state.started ? 2 : 1; // h: 2 started, 1 waiting
        return d(lobby.players, started);
      }
      if (p === "/api/start") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return d(9, 9);
        const seat = seatOf(lobby, q.get("tok"));
        if (seat < 0) return d(9, 3);
        const r = durakStart(lobby, seat);
        if (!r.ok) return d(9, r.code);
        lobby.t = nowSeq();                                  // keep-alive: TTL from last activity
        await this.storage.put("l:" + code, lobby);
        return d(1, 1);
      }
      if (p === "/api/dact") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return d(9, 9);
        const seat = seatOf(lobby, q.get("tok"));
        if (seat < 0) return d(9, 3);
        const a = clampInt(q.get("a"), 0, 1, 4);
        const pr = clampInt(q.get("p"), 0, 0, 5);
        const c = clampInt(q.get("c"), 0, 0, 35);
        const r = durakAct(lobby, seat, a, pr, c);
        if (!r.ok) return d(9, r.code);
        lobby.t = nowSeq();                                  // keep-alive: TTL from last activity
        await this.storage.put("l:" + code, lobby);
        return d(1, 1);
      }
      if (p === "/api/dlog") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return d(9, 9);
        const since = clampInt(q.get("since"), 0, 0, 100000);
        const ev = lobby.state && lobby.state.pub ? lobby.state.pub[since] : null;
        if (!ev) return d(1, 1);                           // nothing new (no event is (1,1))
        return d(ev.w, ev.h);
      }
      if (p === "/api/ddraw") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return d(9, 9);
        const seat = seatOf(lobby, q.get("tok"));
        if (seat < 0) return d(9, 3);                      // only your own seat's private cards
        const i = clampInt(q.get("i"), 0, 0, 100000);
        const priv = lobby.state && lobby.state.priv ? lobby.state.priv[seat] : null;
        const card = priv ? priv[i] : undefined;
        if (card === undefined || card === null) return d(1, 1); // no card at that index yet
        return d(card + 2, 1);
      }

      // ── Durak N-seat private lobby (2–4 players) ─────────────────────────────────
      // Mirrors the poker lobby routes (pcreate/pjoin/proom): the 2-int move/poll lobby is
      // hard-capped at 2 seats, so a 3–4-player table needs its OWN create/join/room that seats
      // up to `cap`. Once dealt, play runs through the SAME /api/start · /api/dact · /api/dlog ·
      // /api/ddraw handlers above — those are seat-token + state driven and seat-count agnostic,
      // so nothing about the game protocol changes; only lobby formation grows past two seats.
      if (p === "/api/dcreate") {
        await this.maybeSweep();
        if (!validTok(q.get("tok"))) return d(9, 3);
        const cap = clampInt(q.get("n"), 2, 2, 4);           // seat cap 2..4
        const newCode = await this.freshCode();
        const lobby = {
          game: 3, players: 1, moves: [], pub: 0, t: nowSeq(), cap: cap,
          seats: [{ tok: q.get("tok") || "" }],              // host = seat 0
          turn: 0,
          state: initState(3)
        };
        await this.storage.put("l:" + newCode, lobby);
        // HOST (+100 on width, like create) · height carries the seat cap so the joiner UI
        // can show "waiting 1/N" without another round-trip.
        return dCode(newCode, true);
      }
      if (p === "/api/djoin") {
        if (!validTok(q.get("tok"))) return d(9, 3);
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby || lobby.game !== 3 || !lobby.cap) return d(20, 1); // missing / not an N-seat durak lobby
        if (lobby.state && lobby.state.started) return d(22, 1);       // already started
        if (seatOf(lobby, q.get("tok")) >= 0)                           // idempotent re-join (poll safety)
          return d(lobby.cap, lobby.players);
        if (lobby.players >= lobby.cap) return d(21, 1);              // full
        lobby.seats.push({ tok: q.get("tok") || "" });
        lobby.players++;
        lobby.t = nowSeq();
        await this.storage.put("l:" + code, lobby);
        // width = cap, height = the seat index this joiner took +1 (so it learns its seat)
        return d(lobby.cap, lobby.players);
      }
      if (p === "/api/droom") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby || lobby.game !== 3 || !lobby.cap) return d(9, 1); // gone / not an N-seat durak lobby
        const started = lobby.state && lobby.state.started ? ROOM_STARTED : 0;
        // width = players joined (+ROOM_STARTED band once dealt) · height = seat cap
        return d(lobby.players + started, lobby.cap);
      }

      // ── Poker (authoritative dealer, 2–4 players; its own multi-seat lobby) ──────
      // A poker lobby holds up to `cap` seats (chosen at create). Unlike the 2-int games it is
      // NOT capped at 2 — pjoin fills seats up to cap, and the host starts when ready.
      if (p === "/api/pcreate") {
        await this.maybeSweep();
        if (!validTok(q.get("tok"))) return d(9, 3);
        const cap = clampInt(q.get("n"), 2, 2, 4);           // seat cap 2..4
        const newCode = await this.freshCode();
        const lobby = {
          game: 6, players: 1, pub: 0, t: nowSeq(), cap: cap,
          seats: [{ tok: q.get("tok") || "" }],              // host = seat 0
          state: initState(6)
        };
        await this.storage.put("l:" + newCode, lobby);
        // HOST (+100 on width, like create) · height carries the seat cap so the joiner UI
        // can show "waiting 1/N" without another round-trip.
        return dCode(newCode, true);
      }
      if (p === "/api/pjoin") {
        if (!validTok(q.get("tok"))) return d(9, 3);
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby || lobby.game !== 6) return d(20, 1);   // missing / not a poker lobby
        if (lobby.state && lobby.state.started) return d(22, 1); // already started
        if (seatOf(lobby, q.get("tok")) >= 0)                // idempotent re-join (poll safety)
          return d(lobby.cap || 4, lobby.players);
        if (lobby.players >= (lobby.cap || 4)) return d(21, 1); // full
        lobby.seats.push({ tok: q.get("tok") || "" });
        lobby.players++;
        lobby.t = nowSeq();
        await this.storage.put("l:" + code, lobby);
        // width = cap, height = the seat index this joiner took +1 (so it learns its seat)
        return d(lobby.cap || 4, lobby.players);
      }
      if (p === "/api/proom") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby || lobby.game !== 6) return d(9, 1);    // gone
        const started = lobby.state && lobby.state.started ? ROOM_STARTED : 0;
        // width = players joined (+ROOM_STARTED band once started) · height = seat cap
        return d(lobby.players + started, lobby.cap || 4);
      }
      if (p === "/api/pstart") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby || lobby.game !== 6) return d(9, 9);
        const seat = seatOf(lobby, q.get("tok"));
        if (seat < 0) return d(9, 3);
        const r = pokerStart(lobby, seat);
        if (!r.ok) return d(9, r.code);
        lobby.t = nowSeq();
        await this.storage.put("l:" + code, lobby);
        return d(1, 1);
      }
      if (p === "/api/pact") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby || lobby.game !== 6) return d(9, 9);
        const seat = seatOf(lobby, q.get("tok"));
        if (seat < 0) return d(9, 3);
        const a = clampInt(q.get("a"), 0, 0, 3);
        const to = clampInt(q.get("to"), 0, 0, 5000);
        const r = pokerAct(lobby, seat, a, to);
        if (!r.ok) return d(9, r.code);
        lobby.t = nowSeq();
        await this.storage.put("l:" + code, lobby);
        return d(1, 1);
      }
      if (p === "/api/pnext") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby || lobby.game !== 6) return d(9, 9);
        const seat = seatOf(lobby, q.get("tok"));
        if (seat < 0) return d(9, 3);
        const r = pokerNext(lobby, seat);
        if (!r.ok) return d(9, r.code);
        lobby.t = nowSeq();
        await this.storage.put("l:" + code, lobby);
        return d(1, 1);
      }
      if (p === "/api/plog") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby || lobby.game !== 6) return d(9, 9);
        const since = clampInt(q.get("since"), 0, 0, 100000);
        const ev = lobby.state && lobby.state.log ? lobby.state.log[since] : null;
        if (!ev) return d(1, 1);                           // nothing new
        return d(ev.w, ev.h);
      }
      if (p === "/api/pdraw") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby || lobby.game !== 6) return d(9, 9);
        const seat = seatOf(lobby, q.get("tok"));
        if (seat < 0) return d(9, 3);
        const i = clampInt(q.get("i"), 0, 0, 1);             // exactly 2 hole cards (0,1)
        const hole = lobby.state && lobby.state.serverHole ? lobby.state.serverHole[seat] : null;
        const card = hole ? hole[i] : undefined;
        if (card === undefined || card === null) return d(1, 1);
        return d(card + 2, 1);                             // card+2, like ddraw
      }

      return d(9, 8); // unknown route
    } catch (e) {
      return d(9, 7); // server error marker
    }
  }

  async freshCode() {
    // Lobby code, rebased to 0..CODE_MAX (was 1000..9999). The whole code must ride DOWN in
    // one image on create/quick, and the level-quantised downlink caps a code at CODE_MAX
    // (=CODE_HI_MAX*64+63) so it can be split into two 6-bit halves (see codePng/CODE_*).
    // Random probes first, then a full linear scan as a fallback so we never clobber a live
    // lobby. Storage keys are "l:"+int, so a minted int and a client-typed code that
    // validCode canonicalised to the same int-string land on the same key.
    for (let i = 0; i < 200; i++) {
      const c = Math.floor(Math.random() * (CODE_MAX + 1));
      const existing = await this.storage.get("l:" + c);
      if (!existing) return c;
    }
    for (let c = 0; c <= CODE_MAX; c++) {
      const existing = await this.storage.get("l:" + c);
      if (!existing) return c;
    }
    return -1; // server full (extremely unlikely); create surfaces it as a broken mint
  }

  // Seat a joiner into a waiting host lobby, FIXING the game if the host was a still-
  // undecided multi-select lobby (game 0 → the picked game, and initialise its board now
  // that we know which engine it needs). Clears EVERY per-game queue the host held, so a
  // multi-lobby registered under several games can never be double-joined.
  async finalizeJoin(waitCode, w, tok, game) {
    if (w.game === 0) { w.game = game; w.games = null; w.state = initState(game); }
    w.players = 2;
    w.seats = w.seats || [null, null];
    w.seats[1] = { tok: tok || "" };           // joiner takes seat 1
    initClock(w);                              // (re)anchor the bank to the JOIN moment, so a host that
                                               // waited in the public queue isn't billed for idle matchmaking
    await this.storage.put("l:" + waitCode, w);
    await this.clearQueuesFor(w, waitCode);
  }

  // Remove a lobby's code from every public queue it registered under. Three queue shapes:
  //   • single-quick  → one (game, tc-bucket) slot stored in lobby.qk (pubq:q:<game>:<bucket>)
  //   • multi-select  → one pubq:<game> per candidate game in lobby.games[]
  // Only deletes a queue entry that still points at THIS code (a newer host may have replaced
  // it). Both shapes are cleared idempotently, so a mislabeled lobby can't strand a slot.
  async clearQueuesFor(lobby, code) {
    if (lobby.qk) {
      const wc = await this.storage.get(lobby.qk);
      if (wc != null && Number(wc) === Number(code)) await this.storage.delete(lobby.qk);
    }
    const ids = lobby.games && lobby.games.length ? lobby.games : [lobby.game];
    for (let i = 0; i < ids.length; i++) {
      const g = ids[i];
      if (!g) continue;
      const wc = await this.storage.get("pubq:" + g);
      if (wc != null && Number(wc) === Number(code)) await this.storage.delete("pubq:" + g);
    }
  }


  // Opportunistic cleanup so a public relay's storage stays bounded. Runs at most
  // once a minute (guarded by a stored timestamp) and only off write paths
  // (create/quick), never on the hot poll loop. Drops lobbies idle for > 30 min.
  async maybeSweep() {
    const now = Date.now();
    const last = (await this.storage.get("lastSweep")) || 0;
    if (now - last < 60000) return;
    await this.storage.put("lastSweep", now);
    const all = await this.storage.list({ prefix: "l:" });
    for (const [key, lobby] of all) {
      if (lobby && lobby.t && now - lobby.t > 30 * 60000) {
        await this.storage.delete(key);
      }
    }
  }
}

function clampInt(v, dflt, lo, hi) {
  const n = parseInt(v, 10);
  if (isNaN(n)) return dflt;
  return Math.max(lo, Math.min(hi, n));
}

// A seat token must be a non-empty, sanely-bounded alphanumeric string. Rejecting junk /
// empty tokens stops us from ever creating an unusable "occupied but tokenless" seat (a
// seat whose empty tok makes seatOf return -1 forever), and the length cap keeps a caller
// from bloating Durable Object storage with a giant token. The client mint is 48 hex-ish
// chars (see MG.Session.newToken), comfortably inside these bounds.
function validTok(tok) {
  return typeof tok === "string" && tok.length >= 8 && tok.length <= 64 && /^[a-z0-9]+$/i.test(tok);
}

// Canonicalise an incoming lobby code. Codes are ints 0..CODE_MAX (see freshCode); the
// client sends the code as plain decimal digits. Parse strictly (1..4 digits, no signs/
// exponents/unicode), range-check, and return the CANONICAL int-string so a lookup key
// always matches the mint key regardless of zero-padding ("0042" and "42" → "42"). Out
// of range or malformed → "" so every `code ? …` guard falls to the missing/gone branch.
function validCode(raw) {
  if (typeof raw !== "string" || !/^[0-9]{1,4}$/.test(raw)) return "";
  const n = parseInt(raw, 10);
  return n >= 0 && n <= CODE_MAX ? String(n) : "";
}

// Lobby codes are rebased to 0..CODE_MAX so they fit the level-quantised downlink (a
// dimension carries a level 0..63; see the `d()` encoder). A code splits into hi=code>>6
// (0..15) on the width and lo=code&63 on the height. The width is OFFSET into a dedicated
// BAND — joiner/create at 24, host at 40 — so it can never land on an error sentinel
// (9 busy/err · 20 missing · 21 full · 22 started) or the (1,1) ok marker. Host vs joiner
// is thus the band, not a fragile +100. Client mirror: mg_net.js decodeCode().
const CODE_MAX = 1023;
const CODE_BAND_JOIN = 24;   // width 24..39 → joiner/create
const CODE_BAND_HOST = 40;   // width 40..55 → host (role flag folded into the band)
// proom/droom fold the "started" flag into the WIDTH as a band offset (was +100, which
// overflows a level): waiting → players 1..4, started → 51..54. Clear of every sentinel
// (1 ok · 9 err · 20/21/22 formation) and <=63. Client mirror: mg_net.js proom/droom.
const ROOM_STARTED = 50;
// Clocks band: a real per-seat reading is width 30..39 (hi = sec>>6, 0..9), height 0..63.
// 30 sits clear of the code bands (24..55 overlaps, but /api/clocks never returns a code)
// and clear of the {1,9,20,21,22} sentinel widths, so a live clock is never a sentinel.
const CLK_BASE = 30;
function dCode(code, isHost) {
  return d((isHost ? CODE_BAND_HOST : CODE_BAND_JOIN) + ((code >> 6) & 15), code & 63);
}

// ── per-IP rate limit for lobby FORMATION + existence-probe routes ────────────
// Window/cap are tuned so no legitimate flow comes close: a single client makes ~1
// create/quick plus ~1 status|room poll per ~1.5 s (≈8 hits/10 s), and even several
// players sharing one NAT/household IP stay well under RL_MAX_HITS. A brute-forcer
// sweeping the 9000-code space or flooding `create` is one IP and gets capped to
// RL_MAX_HITS/window (≈6 req/s → ~25 min for a full sweep — a real deterrent, and H2
// already blocks multi-seat lobbies from a guessed join). RL_MAX_IPS bounds the map so
// a spoofed-IP flood can't grow it without bound. The in-game hot loop (move/poll/log/
// draw/clocks/rematch) is NEVER gated — a (9,x) throttle sentinel there would be
// misread by the poll decoder as a real move (from=8,to=4) and corrupt the board.
const RL_WINDOW_MS = 10000;   // sliding window length
const RL_MAX_HITS = 60;       // max FORMATION/probe hits per IP per window
const RL_MAX_IPS = 5000;      // cap on tracked IPs (memory bound)
// Hard ceiling on a lobby's monotonic event array (moves[] for the 2-int games, log[] for
// poker). poll/plog `since` indexes these directly, so they can NEVER be truncated — instead
// we refuse to grow them past a size no honest game reaches (a full chess/checkers game is
// well under 600 plies; a 200-chip poker table ends in far fewer events). Only two colluding
// seats deliberately bloating the single DO's storage ever hit it. Reject as illegal past it.
const MOVE_CAP = 4000;
// Routes the limiter guards. Formation (create + every join variant) is the DoS +
// brute-force-join vector; the existence probes (status/room/proom/droom) are how a
// sweeper discovers which of the 9000 codes are live. Everything else — probe/ping
// (calibration must always work), cancel (frees lobbies), and the whole in-game loop —
// is intentionally exempt.
const THROTTLED_ROUTES = {
  "/api/create": 1, "/api/quick": 1, "/api/mquick": 1, "/api/join": 1,
  "/api/pcreate": 1, "/api/pjoin": 1, "/api/dcreate": 1, "/api/djoin": 1,
  "/api/status": 1, "/api/room": 1, "/api/proom": 1, "/api/droom": 1
};

// Game ids the generic /api/create lobby accepts. 3 = durak creates its lobby here too, then
// switches to its own dealer routes (room/start/dact/…). 6 = poker is DELIBERATELY absent: it
// owns a fully separate route set (pcreate/pjoin/pstart/pact/…) because the generic lobby is
// hard-capped at 2 seats and poker seats 2–4. An id outside this set has no engine, so
// create/quick reject it up front and move never relays it.
const SUPPORTED_GAMES = { 1: 1, 2: 1, 3: 1, 4: 1, 5: 1 };

// Games eligible for MULTI-select quick match. Durak (3) is excluded: it uses a wholly
// separate route set (room/start/dact/…), so it can't share the 2-int move/poll lobby a
// multi-lobby becomes. Parse "1,2,4,5" → a de-duplicated, sorted array of valid ids.
const MQUICK_GAMES = { 1: 1, 2: 1, 4: 1, 5: 1 };
function parseGameSet(raw) {
  if (!raw) return [];
  const parts = String(raw).split(",");
  const seen = {}, out = [];
  for (let i = 0; i < parts.length; i++) {
    const n = parseInt(parts[i], 10);
    if (!isNaN(n) && MQUICK_GAMES[n] && !seen[n]) { seen[n] = 1; out.push(n); }
  }
  out.sort(function (a, b) { return a - b; });
  return out;
}


// ── authoritative game clocks ────────────────────────────────────────────────
// Only chess (4) and checkers (1) run a time bank; the picker offers 1/3/5/10 min. tc is
// stored in SECONDS (fits one downlink int: 600 < ~1000). Any other value / game → 0 = no
// clock (TTT/Durak/C4 use their own per-move rule client-side). QUICK forces a fixed 5 min.
const CLOCK_GAMES = { 1: 1, 4: 1 };
const CLOCK_CHOICES = { 60: 1, 180: 1, 300: 1, 600: 1 };
const QUICK_CLOCK_SEC = { 1: 300, 4: 300 };
function clockSecFor(game, raw) {
  if (!CLOCK_GAMES[game]) return 0;
  const n = parseInt(raw, 10);
  return CLOCK_CHOICES[n] ? n : 0;   // reject anything not on the menu (0 = play untimed)
}
// The time control is one of a tiny fixed menu, so it rides the downlink as a small INDEX
// (0..4) rather than raw seconds (0..600 would overflow one level dimension). Client mirror:
// mg_net.js TC_SECS. Index 0 = untimed; 1..4 = 60/180/300/600 s.
const TC_SECS = [0, 60, 180, 300, 600];
function tcIndex(sec) { const i = TC_SECS.indexOf(sec | 0); return i < 0 ? 0 : i; }

// The bank is stored as remaining MILLISECONDS per seat plus, while a side is on the move,
// the wall-clock ms at which its turn began (runStart). remaining(seat) = stored ms minus
// the elapsed run of the active seat, floored at 0. Because both clients read the SAME
// server time via /api/clocks, neither can drift out of agreement and the server alone
// decides flag-fall (remaining hits 0). No clock → clkMs stays null and everything is a no-op.
function initClock(lobby) {
  if (!lobby.tc) { lobby.clkMs = null; return; }
  lobby.clkMs = [lobby.tc * 1000, lobby.tc * 1000];
  lobby.clkRun = 0;                 // seat currently ticking (seat 0 = host moves first)
  lobby.clkStart = Date.now();      // wall-clock ms when the running seat's turn began
  lobby.clkFlag = -1;               // seat that flagged (-1 = nobody yet)
}
// Charge the running seat for the time elapsed since its turn began, and (if `handoff`)
// start the other seat's turn. Call on every accepted move BEFORE reading/persisting.
function clockCharge(lobby, handoff, nextSeat) {
  if (!lobby.clkMs) return;
  const now = Date.now();
  const run = lobby.clkRun;
  lobby.clkMs[run] = Math.max(0, lobby.clkMs[run] - (now - lobby.clkStart));
  if (lobby.clkMs[run] === 0 && lobby.clkFlag < 0) lobby.clkFlag = run;
  if (handoff) { lobby.clkRun = nextSeat; lobby.clkStart = now; }
  else lobby.clkStart = now;        // mid-chain: same seat keeps running, reset the anchor
}
// Remaining SECONDS for a seat right now (rounded up so a live "0:01" isn't shown as flagged
// until it truly hits 0). Reflects the running seat's elapsed time without mutating storage.
function clockSec(lobby, seat) {
  if (!lobby.clkMs) return -1;      // -1 = untimed (client shows no clock)
  let ms = lobby.clkMs[seat];
  if (seat === lobby.clkRun && lobby.clkFlag < 0) ms = Math.max(0, ms - (Date.now() - lobby.clkStart));
  return Math.ceil(ms / 1000);
}
// Has the running seat's bank expired as of now? Persist the flag so the result sticks.
function clockCheckFlag(lobby) {
  if (!lobby.clkMs || lobby.clkFlag >= 0) return lobby.clkFlag;
  const run = lobby.clkRun;
  if (lobby.clkMs[run] - (Date.now() - lobby.clkStart) <= 0) { lobby.clkMs[run] = 0; lobby.clkFlag = run; }
  return lobby.clkFlag;
}

function nowSeq() {
  // Monotonic-ish tag for debugging; not used for logic.
  return Date.now();
}

/* ───────────────── authoritative identity + move validation ─────────────────
 * The seat token is the trust anchor. It flows ONLY upward (query param), is never
 * echoed in a response, and is long + random, so an observer can neither read nor
 * guess it. seatOf maps a presented token to its seat index (0/1) or -1 (→ (9,3)).
 * Fixed seat↔side mapping (matches the client): seat 0 = host, moves first.
 */
function rules() { return (typeof globalThis !== "undefined" && globalThis.MGRules) || {}; }

function seatOf(lobby, tok) {
  if (!tok || !lobby.seats) return -1;
  for (let i = 0; i < lobby.seats.length; i++) {
    const s = lobby.seats[i];
    if (s && s.tok && s.tok === tok) return i;
  }
  return -1;
}

// Fresh authoritative state per game. null = no server engine → legacy relay.
function initState(game) {
  const R = rules();
  if (game === 1) return { board: R.checkers.initialBoard(), chainSq: -1 }; // checkers
  if (game === 2) return { board: [0, 0, 0, 0, 0, 0, 0, 0, 0] };            // tic-tac-toe
  if (game === 4) return { board: R.chess.initialChessBoard(), cst: R.chess.initialChessState() }; // chess
  if (game === 3) return { started: 0, pub: [], priv: [[], []] };                                  // durak (dealt on /api/start)
  if (game === 5) return { board: R.connectfour.initialBoard() };                                  // connect four
  if (game === 6) return { started: 0, pub: [], priv: [], st: null, stacks: null, button: -1 };    // poker (dealt on /api/pstart)
  return null;
}

// Validate a move by the seat holder against the authoritative state. Returns
// { ok:true, move:{f,t,e} } (e computed by the SERVER) or { ok:false, code } where
// code is 1 (not your turn) or 2 (illegal move). Mutates lobby.state / lobby.turn on
// acceptance. A game with no server engine relays unchecked (backward compatible).
function validateMove(lobby, seat, from, to, end) {
  const R = rules();
  // No authoritative engine for this lobby → REJECT. We never blindly relay an unchecked
  // move (that would make the server a dumb, cheatable relay for any unknown game id).
  if (!lobby.state) return { ok: false, code: 2 };
  if (lobby.game === 1) return validateCheckers(R.checkers, lobby, seat, from, to);
  if (lobby.game === 2) return validateTtt(lobby, seat, from, to);
  if (lobby.game === 4) return validateChess(R.chess, lobby, seat, from, to);
  if (lobby.game === 5) return validateConnectFour(R.connectfour, lobby, seat, from, to);
  return { ok: false, code: 2 };
}


function validateCheckers(RC, lobby, seat, from, to) {
  const st = lobby.state, b = st.board;
  const side = seat === 0 ? RC.WHITE : RC.BLACK;
  const chaining = st.chainSq >= 0;
  // Turn: mid-chain only the chaining seat may move, and only its chain piece.
  if (chaining) { if (seat !== lobby.turn || from !== st.chainSq) return { ok: false, code: 1 }; }
  else if (seat !== lobby.turn) return { ok: false, code: 1 };
  if (RC.colorOf(b[from]) !== side) return { ok: false, code: 2 };
  // Legal targets for THIS piece, honouring forced capture / an active chain.
  let targets;
  if (chaining || RC.anyCaptureFor(b, side)) targets = RC.captureMoves(b, from);
  else targets = RC.simpleMoves(b, from);
  let ok = false;
  for (let i = 0; i < targets.length; i++) if (targets[i].to === to) { ok = true; break; }
  if (!ok) return { ok: false, code: 2 };
  const res = RC.applyHop(b, from, to); // mutates the authoritative board
  // Same piece may keep jumping (a capture, and not just crowned) → chain continues.
  const more = res.captured && !res.promoted && RC.captureMoves(b, to).length > 0;
  let e;
  if (more) { st.chainSq = to; e = 0; }                       // turn stays with this seat
  else { st.chainSq = -1; e = 1; lobby.turn = seat === 0 ? 1 : 0; } // hand off
  return { ok: true, move: { f: from, t: to, e: e } };
}

function validateTtt(lobby, seat, from, to) {
  const R = rules();
  const b = lobby.state.board;
  if (seat !== lobby.turn) return { ok: false, code: 1 };
  // Reject any move once the game is already decided (a win line or a full board), so a
  // loser can't keep placing marks and corrupt the finished log.
  if (R.ttt.tttWinner(b) || R.ttt.tttFull(b)) return { ok: false, code: 2 };
  // A placement is cell 0..8 with the fixed marker to===9, onto an empty cell.
  if (to !== 9 || from < 0 || from > 8 || b[from] !== 0) return { ok: false, code: 2 };

  b[from] = seat === 0 ? 1 : 2;              // X (host) / O (joiner)
  lobby.turn = seat === 0 ? 1 : 0;
  return { ok: true, move: { f: from, t: 9, e: 1 } };
}

function validateChess(RX, lobby, seat, from, to) {
  const st = lobby.state;
  const side = seat === 0 ? 1 : -1;          // white / black
  if (seat !== lobby.turn) return { ok: false, code: 1 };
  if (RX.cSign(st.board[from]) !== side) return { ok: false, code: 2 };
  const legal = RX.legalMoves(st.board, st.cst, side); // includes self-check filter, castling, ep
  let ok = false;
  for (let i = 0; i < legal.length; i++) if (legal[i].from === from && legal[i].to === to) { ok = true; break; }
  if (!ok) return { ok: false, code: 2 };
  const r = RX.makeMove(st.board, st.cst, from, to);
  st.board = r[0]; st.cst = r[1];
  lobby.turn = seat === 0 ? 1 : 0;           // every chess move ends the turn
  return { ok: true, move: { f: from, t: to, e: 1 } };
}

// Connect Four: a move is a COLUMN in `from` (0..6) with the fixed marker `to === 7` (so
// from != to always holds, exactly like tic-tac-toe's to === 9). The server derives the
// landing row via gravity and rejects a full column. Host = seat 0 = red, moves first.
function validateConnectFour(RC, lobby, seat, from, to) {
  const st = lobby.state;
  if (seat !== lobby.turn) return { ok: false, code: 1 };
  if (RC.winner(st.board) || RC.isFull(st.board)) return { ok: false, code: 2 }; // game already over
  if (to !== 7 || from < 0 || from >= RC.COLS) return { ok: false, code: 2 };

  const r = RC.drop(st.board, from, seat === 0 ? 1 : 2);
  if (!r) return { ok: false, code: 2 };     // column full
  st.board = r.board;
  lobby.turn = seat === 0 ? 1 : 0;
  return { ok: true, move: { f: from, t: 7, e: 1 } };
}

/* ─────────────────── Durak authoritative dealer (2–4 players) ──────────────────────
 * Public event encoding (each fits the 2-int downlink, both dims <= ~63; NONE is (1,1)):
 *   TRUMP        (2,  trumpCard+1)
 *   OPEN atk a   (3,  a+1)                     first attacker seat
 *   ROLES a d    (4,  a*4 + d + 1)             post-bout roles: attacker a, defender d (0..3)
 *   PLAY  s c    (10+s, c+1)                   seat s attacks/throws in card c (s 0..3)
 *   COVER p c    (20+p, c+1)                   defender covers table pair p with card c (p 0..5)
 *   TAKE  s      (30+s, 1)                     seat s (defender) takes the table (s 0..3)
 *   BITO         (40,   1)                     table beaten & discarded
 *   DRAW  s n    (50+s, n+1)                   seat s drew n cards from the deck (s 0..3)
 *   OVER  L      (60,   L+2)                   game over; L = fool seat (-1 = draw)
 * ROLES makes the SERVER authoritative over the post-bout rotation (who attacks/defends next),
 * which for 3–4 players depends on refill order + who ran out of cards — state the client can't
 * replay. The 2-player wire is unchanged except for this one extra event after each bout.
 * Private per-seat draws go to state.priv[seat] and are pulled one index at a time via
 * /api/ddraw (gated by the seat token), encoded as (card+2, 1). The +2 is deliberate:
 * card id 0 would otherwise collide with the universal (1,1) "nothing new" marker.
 */
function dpush(st, w, h) { st.pub.push({ w: w, h: h }); }

function durakStart(lobby, seat) {
  const R = rules().durak;
  const st = lobby.state;
  if (!st || st.started) return { ok: true };            // idempotent (already dealt)
  if (seat !== 0) return { ok: false, code: 1 };         // only the host (seat 0) starts
  const n = lobby.players;                               // deal for however many actually seated (2..4)
  if (n < 2) return { ok: false, code: 2 };              // need at least two players
  const seedBuf = new Uint32Array(1); crypto.getRandomValues(seedBuf);
  const seed = seedBuf[0] & 0x7fffffff;                  // SERVER owns the seed (never sent down)
  const g = R.newGame(n, seed);

  st.numPlayers = n;
  st.trump = g.trump; st.trumpCard = g.trumpCard;
  st.deck = g.deck; st.hands = g.hands; st.table = g.table;
  st.attacker = g.attacker; st.defender = g.defender; st.phase = g.phase;
  st.discard = g.discard; st.out = g.out; st.loser = g.loser;
  st.passed = g.passed;                                  // throw-in consensus flags (per seat)
  st.pub = []; st.priv = [];
  for (let s = 0; s < n; s++) st.priv.push([]);
  st.started = 1;
  dpush(st, 2, g.trumpCard + 1);                         // TRUMP
  dpush(st, 3, g.attacker + 1);                          // OPEN(first attacker)
  for (let s = 0; s < n; s++) {
    for (let k = 0; k < g.hands[s].length; k++) st.priv[s].push(g.hands[s][k]);
    dpush(st, 50 + s, g.hands[s].length + 1);            // DRAW(s, 6)
  }
  return { ok: true };
}

// Resolve a bout, then emit DRAW events for the DECK cards each seat picked up during
// refill. A card drawn from the deck is one now in a hand that WAS in the pre-bout deck
// (hands and deck are disjoint before the bout), so hand_after ∩ deckBefore = the draws.
// Table cards a taker picks up were already public, so they are NOT re-emitted.
function durakEndBout(st, took) {
  const R = rules().durak;
  const before = {};
  for (let i = 0; i < st.deck.length; i++) before[st.deck[i]] = 1;
  R.endBout(st, took);
  for (let s = 0; s < st.numPlayers; s++) {
    const drawn = [];
    for (let k = 0; k < st.hands[s].length; k++) if (before[st.hands[s][k]]) drawn.push(st.hands[s][k]);
    if (drawn.length) {
      for (let d = 0; d < drawn.length; d++) st.priv[s].push(drawn[d]);
      dpush(st, 50 + s, drawn.length + 1);               // DRAW(s, n)
    }
  }
  if (st.phase === "over") { dpush(st, 60, st.loser + 2); return; }  // OVER(loser)
  // ROLES(attacker, defender): the SERVER owns the post-bout rotation (it depends on refill,
  // who went `out`, and skip-the-taker rules — all card-state the client can't replay). Emitting
  // it authoritatively frees the client from a fragile local swap, which is only correct for 2
  // players. Encoded as (4, attacker*4 + defender + 1); attacker/defender ∈ 0..3 → h ∈ 1..16.
  dpush(st, 4, st.attacker * 4 + st.defender + 1);
}

// A seat abandons a live durak table. Mirrors durakEndBout's DRAW accounting: snapshot the deck,
// run the shared leaveSeat rule (voids the bout, refills survivors, rotates roles), then emit the
// LEFT event, a DRAW per seat that picked up from the deck, and the authoritative post-leave ROLES
// (or OVER when one player remains). Deterministic → clients replay it off the public log.
function durakLeave(lobby, seat) {
  const R = rules().durak;
  const st = lobby.state;
  if (!st || !st.started || st.phase === "over") return;
  if (st.out[seat]) return;                                 // already gone (idempotent)
  const before = {};
  for (let i = 0; i < st.deck.length; i++) before[st.deck[i]] = 1;
  R.leaveSeat(st, seat);
  dpush(st, 45 + seat, 1);                                  // LEFT(seat)
  for (let s = 0; s < st.numPlayers; s++) {
    const drawn = [];
    for (let k = 0; k < st.hands[s].length; k++) if (before[st.hands[s][k]]) drawn.push(st.hands[s][k]);
    if (drawn.length) {
      for (let d = 0; d < drawn.length; d++) st.priv[s].push(drawn[d]);
      dpush(st, 50 + s, drawn.length + 1);                 // DRAW(s, n)
    }
  }
  if (st.phase === "over") { dpush(st, 60, st.loser + 2); return; }  // OVER(loser)
  dpush(st, 4, st.attacker * 4 + st.defender + 1);         // ROLES(attacker, defender)
}

// A seat abandons a live poker table. Folds them out of the current hand and forfeits their chips
// (leaveSeat sets stack 0 → newHand sits them out forever) via the shared rule, emits LEFT(seat),
// then flushes the board/showdown/WIN the fold may have triggered — exactly like a normal fold.
function pokerLeave(lobby, seat) {
  const R = rules().poker;
  const s = lobby.state;
  if (!s || !s.started) return;
  s.log = s.log || [];
  if (s.st) R.leaveSeat(s.st, seat);
  else if (s.stacks) s.stacks[seat] = 0;                   // between hands: just forfeit the stack
  s.log.push({ w: 50 + seat, h: 1 });                      // LEFT(seat)
  if (s.st && !s.handOver) pokerFlush(lobby);              // fold may have ended the hand
}

// Validate + apply one durak action by the seat holder. a: 1 attack, 2 cover, 3 take, 4 bito.
function durakAct(lobby, seat, a, p, c) {
  const R = rules().durak;
  const st = lobby.state;
  if (!st || !st.started || st.phase === "over") return { ok: false, code: 2 };
  if (a === 1) {                                         // attack / throw-in
    if (!R.canAttackWith(st, seat, c)) {
      // distinguish "not your role/turn" from "illegal card" for a friendlier client message
      if (seat === st.defender) return { ok: false, code: 1 };
      return { ok: false, code: 2 };
    }
    R.applyAttack(st, seat, c);
    dpush(st, 10 + seat, c + 1);
    return { ok: true };
  }
  if (a === 2) {                                         // cover a table pair
    if (seat !== st.defender) return { ok: false, code: 1 };
    if (!R.canDefendPair(st, p, c)) return { ok: false, code: 2 };
    R.applyDefend(st, p, c);                              // resets throw-in passes (fresh window)
    dpush(st, 20 + p, c + 1);
    // Only auto-beat if canBito already holds — under the explicit-Bito rule that's only when every
    // remaining attacker holds NO cards. An attacker still holding cards must send its own PASS
    // (Bito) first, so the covered table stays visible until confirmed instead of being swept to
    // discard the instant the defence lands.
    if (R.canBito(st)) { dpush(st, 40, 1); durakEndBout(st, false); }
    return { ok: true };
  }
  if (a === 3) {                                         // take
    if (seat !== st.defender) return { ok: false, code: 1 };
    if (st.table.length === 0) return { ok: false, code: 2 };
    dpush(st, 30 + seat, 1);
    durakEndBout(st, true);
    return { ok: true };
  }
  if (a === 4) {                                         // pass / knock ("done adding to this table")
    // Classic podkidnoy: an attack seat declares it won't throw in more. The table is BEATEN
    // (Bito) only once EVERY in-play attack seat has settled (passed or holds no legal throw-in) —
    // NOT the moment the primary attacker knocks. So this records the pass authoritatively and
    // only ends the bout when consensus is reached; otherwise it echoes a PASS event so the other
    // clients update their local `passed` set (which gates their own Pass button + status).
    if (seat === st.defender || st.out[seat]) return { ok: false, code: 1 };
    if (st.table.length === 0 || R.uncoveredCount(st) !== 0) return { ok: false, code: 2 };
    R.applyPass(st, seat);
    if (R.canBito(st)) { dpush(st, 40, 1); durakEndBout(st, false); }
    else dpush(st, 41 + seat, 1);                        // PASS(seat) — window stays open for others
    return { ok: true };
  }
  return { ok: false, code: 2 };
}


/* ─────────────────────── Poker (authoritative dealer, 2–4 players) ──────────────────────
 * Its OWN route set, like Durak, because the 2-int move/poll lobby is hard-capped at 2 seats
 * and poker seats 2–4 with a host "Start" gate. The worker owns the deck, seed, button, and
 * every hole card; it deals hole cards PRIVATELY (via /api/pdraw, card+2 like ddraw) and relays
 * only PUBLIC facts through an indexed event log (/api/plog). The client replays the shared
 * poker.applyAction to reconstruct all betting truth (pot / whose turn / legal actions are
 * card-INDEPENDENT), and fills board + revealed hole cards + winners from the log — so it never
 * needs the deck and can't diverge from the server.
 *
 * Public event log entries (each fits the 2-int downlink; width picks the type, height the
 * payload+1; a real entry can never decode to (1,1) = "nothing new"):
 *   HAND   (2, button+1)                     start a fresh hand, dealer button on `button`
 *   FOLD   (10+seat, 1)                      seat folds
 *   CHECK  (20+seat, 1)                      seat checks
 *   CALL   (30+seat, 1)                      seat calls
 *   RAISE  (40+seat, to&63) + RAISEHI (44+seat, to>>6)   raise TO `to` chips, split into
 *                                            a lo/hi 6-bit pair (to = hi*64 + lo, up to ~800);
 *                                            width 40-47 never reads as (1,1), so no +1 needed
 *   BOARD  (5, card+1)                       one community card revealed (card 0..51)
 *   SHOW   (60+seat, card+1)                 a hole card of `seat` shown at showdown
 *   WIN    (7, 1)                            hand resolved — client runs resolveShowdown/finish
 *   OVER   (8, 1)                            table over (one player has all the chips)
 * Private draw (/api/pdraw?i=): the i-th hole card the caller was dealt this hand → (card+2, 1),
 * or (1,1) if not dealt yet. The client pulls its 2 hole cards each hand exactly like Durak.
 *
 * Action codes for /api/pact (a, to): a = 0 fold · 1 check · 2 call · 3 raise (to=amount).
 */

// Build the authoritative poker state for a lobby that has `n` seated players. Deals the whole
// hand server-side with a per-hand seed, then converts it into a public event stream + private
// hole cards. Returns the fresh `st` (full, with cards) so the caller can persist it.
function pokerNewHand(lobby) {
  const R = rules().poker;
  const s = lobby.state;
  const n = s.n;                                    // seat count fixed at start
  // rotate the button to the next occupied (non-busted) seat
  let button = s.button;
  const stacks = s.stacks.slice();
  // find next seat with chips for the button (first hand: seat 0)
  if (button < 0) button = 0;
  else { for (let k = 1; k <= n; k++) { const c = (button + k) % n; if (stacks[c] > 0) { button = c; break; } } }
  // SECURITY (C1): the seed MUST be a fresh CSPRNG draw per hand — never derived from
  // lobby.t and never chained through pseed. mulberry32 is fully deterministic, so a
  // predictable seed leaks the entire deck order (every seat's hole cards + the full
  // board) before a bet is placed. Same CSPRNG source durakStart uses (see above).
  const seedBuf = new Uint32Array(1); crypto.getRandomValues(seedBuf);
  const seed = seedBuf[0] & 0x7fffffff;             // SERVER owns the seed (never sent down)
  const st = R.newHand(n, button, stacks, PK_SB, PK_BB, seed);
  s.button = st.button;
  // reset the public log for the hand and stash the private hole cards per seat
  s.hole = st.hole.map((h) => h.slice());           // [[c,c],…] server-only until SHOW
  s.drawn = [];                                      // per-seat: how many hole cards pulled
  for (let i = 0; i < n; i++) s.drawn.push(0);
  s.board = [];                                      // revealed community cards (public)
  s.boardShown = 0;                                  // how many BOARD events emitted so far
  s.shownFor = [];                                   // seats whose hole cards were SHOW-n
  // Replace st.hole/deck with an ONLINE shell so the SERVER also tracks betting via the same
  // shared reducer the client uses — guaranteeing identical validation. The server keeps the
  // real cards in s.hole for private dealing + showdown.
  s.st = R.newHand(n, st.button, stacks, PK_SB, PK_BB, null); // online shell (no cards)
  // BUG (2026-07-18, "three identical 2♠ on the flop online"): newHand deals the board LAZILY —
  // st.board is [] until nextStreet shifts cards off the deck. Reading st.board here captured an
  // empty array, so pokerFlush emitted BOARD(undefined) → PNG h=1 → the client decoded card id 0
  // (= 2♠) for every community card. The 5 board cards are the TOP of the freshly-dealt deck AFTER
  // the 2·n hole cards (dealBoard/runout just shift them in flop/turn/river order), so slice them
  // straight off the deck now. Verified byte-identical to the real runout for every seed.
  s.st.__fullBoard = st.deck.slice(0, 5);             // full 5-card board (server reveals on schedule)
  s.serverHole = st.hole;                             // real hole cards for showdown eval
  // The log is CONTINUOUS across hands so the client's `since` cursor stays monotonic — a HAND
  // event just appends and the client reads it as "new hand, pull my hole cards".
  s.log = s.log || [];
  s.handStart = s.log.length;                         // index of THIS hand's HAND event
  s.log.push({ w: 2, h: st.button + 1 });             // HAND event opens the hand
  s.handOver = 0;
  return s;
}

// Push the BOARD events needed to catch the public board up to the online reducer's street,
// then, if the hand has reached showdown/over, emit SHOW + WIN (or just WIN for uncontested).
function pokerFlush(lobby) {
  const R = rules().poker;
  const s = lobby.state;
  const online = s.st;
  // How many board cards should be visible for the current street? A "showdown" (everyone
  // called down / all-in runout) reveals all five. But an uncontested "over" — everyone
  // folded to one player — reveals NOTHING new: no community card is shown for a hand that
  // never reached a showdown (leaking them was the "board appears after a preflop fold" bug).
  const want = online.street === "flop" ? 3
    : online.street === "turn" ? 4
    : (online.street === "river" || online.street === "showdown") ? 5
    : online.street === "over" ? s.boardShown
    : 0;
  while (s.boardShown < want) {
    const card = s.st.__fullBoard[s.boardShown];
    s.board.push(card);
    s.log.push({ w: 5, h: card + 1 });                // BOARD
    s.boardShown++;
  }
  if ((online.street === "showdown" || online.street === "over") && !s.handOver) {
    // Uncontested (everyone folded) → no cards shown, just resolve. Contested showdown → reveal
    // every non-folded contender's two hole cards, then WIN.
    const contenders = [];
    for (let i = 0; i < s.n; i++) if (online.inHand[i] && !online.folded[i]) contenders.push(i);
    if (contenders.length > 1) {
      for (let j = 0; j < contenders.length; j++) {
        const seat = contenders[j];
        for (let c = 0; c < s.serverHole[seat].length; c++)
          s.log.push({ w: 60 + seat, h: s.serverHole[seat][c] + 1 });   // SHOW
      }
    }
    // Resolve on the SERVER's online reducer using the real cards so stacks stay authoritative.
    online.hole = s.serverHole;
    online.board = s.st.__fullBoard.slice(0, 5);
    R.resolveShowdown(online);
    s.stacks = online.stacks.slice();                 // banked result
    s.log.push({ w: 7, h: 1 });                       // WIN — client resolves locally too
    s.handOver = 1;
    // Table over? one seat holds every chip.
    let alive = 0; for (let i = 0; i < s.n; i++) if (s.stacks[i] > 0) alive++;
    if (alive <= 1) { s.log.push({ w: 8, h: 1 }); s.tableOver = 1; }
  }
}

// Blinds for the online table (match the offline controller: SB 5 / BB 10, 200-chip stacks).
const PK_SB = 5, PK_BB = 10, PK_START = 200;

// Host presses Start: fix the seat count to whoever is seated, deal the first hand.
function pokerStart(lobby, seat) {
  const R = rules().poker;
  const s = lobby.state;
  if (!s) return { ok: false, code: 2 };
  if (s.started) return { ok: true };                 // idempotent
  if (seat !== 0) return { ok: false, code: 1 };       // only the host starts
  const n = lobby.players;
  if (n < 2) return { ok: false, code: 2 };            // need at least two seated
  s.n = n;
  s.button = -1;                                       // first hand normalises to seat 0
  s.stacks = [];
  for (let i = 0; i < n; i++) s.stacks.push(PK_START);
  s.started = 1;
  pokerNewHand(lobby);
  return { ok: true };
}

// Validate + apply one betting action by the seat holder. a: 0 fold · 1 check · 2 call · 3 raise.
function pokerAct(lobby, seat, a, to) {
  const R = rules().poker;
  const s = lobby.state;
  if (!s || !s.started || s.handOver) return { ok: false, code: 2 };
  const online = s.st;
  if (online.toAct !== seat) return { ok: false, code: 1 };  // not your turn
  const action = a === 0 ? { type: "fold" }
    : a === 1 ? { type: "check" }
    : a === 2 ? { type: "call" }
    : { type: "raise", to: to | 0 };
  // Snapshot the log length so we can emit the matching public event for the accepted action.
  if (!R.applyAction(online, seat, action)) return { ok: false, code: 2 }; // illegal
  if (a === 0) s.log.push({ w: 10 + seat, h: 1 });
  else if (a === 1) s.log.push({ w: 20 + seat, h: 1 });
  else if (a === 2) s.log.push({ w: 30 + seat, h: 1 });
  else {
    // RAISE. The raise-TO amount reaches the whole stack (~800), which is 10 bits —
    // it can't ride one dimension's 6-bit level. Split into a lo/hi PAIR of events the
    // client restitches: RAISE(40+seat, to&63) then RAISEHI(44+seat, to>>6). Both use
    // RAW 6-bit halves (no +1): width 40..47 can never read as the (1,1) "nothing new"
    // marker, so height 0 is safe. to = hi*64 + lo, capped at MOVE-log growth like any
    // event pair. Client mirror: mg_net.js plog raise/raisehi.
    const t = to | 0;
    s.log.push({ w: 40 + seat, h: t & 63 });
    s.log.push({ w: 44 + seat, h: (t >> 6) & 63 });
  }
  pokerFlush(lobby);
  return { ok: true };
}

// Deal the NEXT hand (any seated client may request it once the current hand is over and the
// table isn't finished). Idempotent per hand via s.handOver.
function pokerNext(lobby, seat) {
  const s = lobby.state;
  if (!s || !s.started) return { ok: false, code: 2 };
  if (!s.handOver) return { ok: false, code: 2 };      // current hand still live
  if (s.tableOver) return { ok: false, code: 2 };
  // Bound the continuous log so two colluding seats can't fold forever to bloat the DO's
  // storage (M3). A real 200-chip table ends in a few dozen hands (< a few hundred events);
  // MOVE_CAP is far above any honest game, so this only ever trips on abuse — after which no
  // new hand is dealt and the table effectively ends where it is.
  if (s.log && s.log.length >= MOVE_CAP) return { ok: false, code: 2 };
  pokerNewHand(lobby);
  return { ok: true };
}


/* ─────────────────────────── LEVEL DOWNLINK ENCODING ───────────────────────────
 * Every DATA response is a "level" per dimension, not a raw integer:
 *   dim = level*STEP + BASE      (STEP=9, BASE=15)
 * WHY: the old dim=int+1 encoding dies on a UI-scaled display. The engine rounds
 * actuallayout, and on scale>1 it biases small sizes UPWARD ~1px, so value 1 renders
 * indistinguishable from 2 — corrupting corner-square moves, the (1,1) marker, and
 * every code half. STEP=9 spaces adjacent levels 9 logical px apart, so a ±2px engine
 * error can't cross a boundary even when a sub-1080p display downscales. Safe range is
 * levels 0..63 (63*9+15 = 582px < the 600px probe envelope, so the host panel is never
 * clamped). Proven across 720p–8K by tools/mg_simulate_resolutions.js. Mirrors
 * mg_net.js decodeLevel EXACTLY. See github2/IMAGE_SIDECHANNEL_1PX_BUG.md.
 *
 * probe stays a LITERAL png(600,1000): it is the calibration reference the client
 * divides by, so it must carry its true pixel size, not a level. Everything else goes
 * through d(w,h). */
const STEP = 9, BASE = 15;
function d(w, h) { return png(w * STEP + BASE, h * STEP + BASE); }

/* ─────────────────────────── PNG encoder ───────────────────────────
 * Emits an 8-bit grayscale PNG of exactly W x H black pixels. Data is all
 * zeros, wrapped in zlib "stored" (uncompressed) deflate blocks — no real
 * compression needed. The client only cares about the dimensions.
 */
function png(w, h) {
  w = Math.max(1, Math.min(w | 0, 8000));
  h = Math.max(1, Math.min(h | 0, 8000));

  const sig = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];
  const ihdr = u32(w).concat(u32(h), [8, 0, 0, 0, 0]); // 8-bit, grayscale

  // Raw scanlines: each row = 1 filter byte (0) + W pixel bytes (0). All zeros.
  const rawLen = h * (1 + w);

  // zlib stream: header + stored deflate blocks + adler32.
  const zlib = [0x78, 0x01];
  let off = 0;
  do {
    const blockLen = Math.min(65535, rawLen - off);
    const final = off + blockLen >= rawLen ? 1 : 0;
    zlib.push(final, blockLen & 255, (blockLen >> 8) & 255,
      ~blockLen & 255, (~blockLen >> 8) & 255);
    for (let i = 0; i < blockLen; i++) zlib.push(0);
    off += blockLen;
  } while (off < rawLen);
  zlib.push(...u32(adler32Zeros(rawLen)));

  const bytes = sig
    .concat(chunk("IHDR", ihdr))
    .concat(chunk("IDAT", zlib))
    .concat(chunk("IEND", []));

  return new Response(new Uint8Array(bytes), {
    headers: {
      "content-type": "image/png",
      "cache-control": "no-store, no-cache, must-revalidate, max-age=0",
      "access-control-allow-origin": "*",
    },
  });
}

function u32(n) {
  return [(n >>> 24) & 255, (n >>> 16) & 255, (n >>> 8) & 255, n & 255];
}

function chunk(type, data) {
  const t = [type.charCodeAt(0), type.charCodeAt(1), type.charCodeAt(2), type.charCodeAt(3)];
  const body = t.concat(data);
  return u32(data.length).concat(body, u32(crc32(body)));
}

// Adler32 of an all-zeros buffer of length n. a stays 1; b = (n * 1) mod 65521.
function adler32Zeros(n) {
  const MOD = 65521;
  const a = 1;
  const b = ((n % MOD) * 1) % MOD; // each step adds a(=1)
  return ((b << 16) | a) >>> 0;
}

let CRC_TABLE = null;
function crc32(bytes) {
  if (!CRC_TABLE) {
    CRC_TABLE = new Uint32Array(256);
    for (let n = 0; n < 256; n++) {
      let c = n;
      for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
      CRC_TABLE[n] = c >>> 0;
    }
  }
  let crc = 0xffffffff;
  for (let i = 0; i < bytes.length; i++) {
    crc = CRC_TABLE[(crc ^ bytes[i]) & 255] ^ (crc >>> 8);
  }
  return (crc ^ 0xffffffff) >>> 0;
}
