/**
 * Deadlock Minigames relay — Cloudflare Worker CORE (authored source).
 *
 * ⚠ DO NOT DEPLOY THIS FILE DIRECTLY. The deploy artifact is `server/worker.js`,
 * generated by `node tools/build_worker.js`, which prepends the SHARED rule engines
 * (panorama/scripts/rules/*.js) so the server validates moves with byte-for-byte the
 * same code the client predicts with. Edit THIS file, then rebuild. See server/README.md.
 *
 * Panorama UI has no fetch / no AsyncWebRequest / no websockets. The ONLY channel
 * back to the client is the intrinsic pixel size of an <Image>: the client sets an
 * image src and reads actuallayoutwidth / actuallayoutheight. So every response here
 * is a tiny PNG whose (width, height) ENCODE two integers.
 *
 * Sending data TO the server is unlimited (URL query params). Only the RESPONSE is
 * squeezed into (width, height). This asymmetry is why the SEAT TOKEN (identity) can
 * flow up freely in the query while the downlink stays two small ints.
 *
 * Transport is strongly consistent because all state lives in ONE Durable Object
 * instance ("hub"). No KV eventual-consistency lag between the two players — ideal for
 * holding the authoritative board copy.
 *
 * Routes (all GET, all return a PNG; pass &rnd=<random> to defeat engine caching):
 *   /api/probe                                    -> (600, 1000)               swap + scale calibration
 *   /api/ping                                     -> (1, 1)                    UI tester route
 *   /api/create?game=G&tok=T                      -> (CODE_HI, CODE_LO+1)      new PRIVATE lobby, host = seat 0
 *   /api/quick?game=G&tok=T                        -> JOINER (CODE_HI, CODE_LO+1) · HOST (CODE_HI+100, CODE_LO+1)
 *   /api/cancel?code=C                            -> (1,1)                     drop a still-waiting lobby
 *   /api/join?code=C&tok=T                         -> (G,1) ok · (20,1) missing · (21,1) full
 *   /api/status?code=C                            -> (players,1) · (9,1) gone
 *   /api/move?code=C&from=F&to=T&end=E&tok=T       -> (1,1) ok · (9,1) not-your-turn · (9,2) illegal · (9,3) bad-token · (9,9) gone
 *   /api/poll?code=C&since=S                       -> (from+1[+100 if end], to+1) · (1,1) nothing new
 *   /api/reset?code=C&game=G&tok=T                 -> (1,1)
 *
 * CODE = CODE_HI*100 + CODE_LO (4-digit). Squares are 0..63; from != to always, so a
 * real poll move can never decode to (1,1) — that's why (1,1) is a safe "nothing" marker.
 * The client polls with since = last applied seq; the returned move is seq = since+1.
 *
 * Move rejection codes all fit the 2-int downlink (width 9 + a small height discriminator):
 *   (9,1) not your turn · (9,2) illegal move · (9,3) bad/foreign token · (9,9) no lobby.
 */

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    if (!url.pathname.startsWith("/api/")) {
      return new Response("Deadlock Minigames relay OK", { status: 200 });
    }
    // All game state lives in a single strongly-consistent Durable Object.
    const id = env.HUB.idFromName("hub");
    const stub = env.HUB.get(id);
    return stub.fetch(request);
  },
};

export class Hub {
  constructor(state) {
    this.state = state;
    this.storage = state.storage;
  }

  async fetch(request) {
    const url = new URL(request.url);
    // Panorama's <Image> loader only fetches URLs that look like an image, so the
    // client appends ".png" to every route. Strip it here before routing.
    const p = url.pathname.replace(/\.png$/, "");
    const q = url.searchParams;
    const code = q.get("code");

    try {
      if (p === "/api/probe") return png(600, 1000);
      if (p === "/api/ping") return png(1, 1);

      if (p === "/api/create") {
        await this.maybeSweep();
        const game = clampInt(q.get("game"), 1, 1, 9);
        if (!SUPPORTED_GAMES[game]) return png(9, 6);      // unsupported game id (6..9 have no engine)

        if (!validTok(q.get("tok"))) return png(9, 3);     // reject empty/garbage seat token
        const newCode = await this.freshCode();

        const lobby = {
          game, players: 1, moves: [], pub: 0, t: nowSeq(),
          seats: [{ tok: q.get("tok") || "" }, null], // seat 0 = host = white/X/+1, moves first
          turn: 0,                                     // seat index whose turn it is
          state: initState(game)                       // authoritative board/state
        };
        await this.storage.put("l:" + newCode, lobby);
        // Split the 4-digit code across both dimensions to keep them small.
        return png(Math.floor(newCode / 100), (newCode % 100) + 1);
      }

      if (p === "/api/quick") {
        await this.maybeSweep();
        const game = clampInt(q.get("game"), 1, 1, 9);
        if (!SUPPORTED_GAMES[game]) return png(9, 6);      // unsupported game id (6..9 have no engine)

        if (!validTok(q.get("tok"))) return png(9, 3);     // reject empty/garbage seat token
        const waitCode = await this.storage.get("pubq:" + game);

        if (waitCode) {
          const w = await this.storage.get("l:" + waitCode);
          if (w && w.pub && w.players < 2) {
            w.players = 2;
            w.seats = w.seats || [null, null];
            w.seats[1] = { tok: q.get("tok") || "" }; // joiner takes seat 1 (black/O/-1)
            await this.storage.put("l:" + waitCode, w);
            await this.storage.delete("pubq:" + game);
            return png(Math.floor(waitCode / 100), (waitCode % 100) + 1); // JOINER (black)
          }
          // stale/closed slot — fall through and host a fresh lobby.
        }
        const newCode = await this.freshCode();
        const lobby = {
          game, players: 1, moves: [], pub: 1, t: nowSeq(),
          seats: [{ tok: q.get("tok") || "" }, null], // host takes seat 0 (white/X/+1)
          turn: 0,
          state: initState(game)
        };
        await this.storage.put("l:" + newCode, lobby);
        await this.storage.put("pubq:" + game, newCode);
        // HOST (white): +100 on the width flags the role without a fragile extra value.
        return png(Math.floor(newCode / 100) + 100, (newCode % 100) + 1);
      }

      if (p === "/api/cancel") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        // Only a SEATED player (valid token) may cancel, and only while the lobby is still
        // waiting for the second player. Never let a 4-digit code-guesser nuke an active match.
        if (lobby && seatOf(lobby, q.get("tok")) >= 0 && lobby.players < 2) {
          await this.storage.delete("l:" + code);
          const waitCode = await this.storage.get("pubq:" + lobby.game);
          if (waitCode != null && Number(waitCode) === Number(code)) {
            await this.storage.delete("pubq:" + lobby.game);
          }
        }
        return png(1, 1);
      }


      if (p === "/api/join") {
        if (!validTok(q.get("tok"))) return png(9, 3); // reject empty/garbage seat token
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return png(20, 1);             // missing
        if (lobby.players >= 2) return png(21, 1); // full

        lobby.players = 2;
        lobby.seats = lobby.seats || [null, null];
        lobby.seats[1] = { tok: q.get("tok") || "" }; // joiner takes seat 1
        await this.storage.put("l:" + code, lobby);
        return png(lobby.game, 1);                 // ok: which game the host picked (1..9)
      }

      if (p === "/api/status") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return png(9, 1);              // gone
        return png(lobby.players, 1);              // 1 or 2
      }

      if (p === "/api/move") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return png(9, 9);              // no lobby
        if (lobby.players < 2) return png(9, 1);   // can't move before the opponent has joined
        const seat = seatOf(lobby, q.get("tok"));
        if (seat < 0) return png(9, 3);            // bad / foreign token — caller isn't a seat here
        const from = clampInt(q.get("from"), 0, 0, 63);
        const to = clampInt(q.get("to"), 0, 0, 63);
        const end = clampInt(q.get("end"), 0, 0, 1);
        // Authoritative validation: the server owns the board, enforces whose turn it is,
        // and rejects any illegal move with a (9,x) code. The stored `end` is the one the
        // SERVER computes (never the client's), so a cheat can't forge the turn hand-off.
        const v = validateMove(lobby, seat, from, to, end);
        if (!v.ok) return png(9, v.code);          // (9,1) not your turn · (9,2) illegal
        lobby.moves.push(v.move);
        lobby.t = nowSeq();                        // keep-alive: TTL is measured from last activity
        await this.storage.put("l:" + code, lobby);
        return png(1, 1);                          // accepted
      }


      if (p === "/api/poll") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return png(9, 9);              // 9x9 signals lobby destroyed / opponent left
        const since = clampInt(q.get("since"), 0, 0, 100000);
        const mv = lobby.moves[since]; // 0-based; this move is seq = since+1
        if (!mv) return png(1, 1);                 // nothing new
        // width = from+1 (+100 if this hop ends the turn); height = to+1.
        // Keeping `end` in a separate hundreds-range (not a low bit) makes it
        // immune to +/-1 rounding from UI scaling. from != to, so never (1,1).
        return png(mv.f + 1 + (mv.e ? 100 : 0), mv.t + 1);
      }

      if (p === "/api/reset") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return png(9, 9);
        if (seatOf(lobby, q.get("tok")) < 0) return png(9, 3); // only a seated player may reset
        // Rematch = same game, fresh state. The game TYPE is fixed at create time and can
        // never be switched mid-lobby (that would desync / void the opponent's board).
        lobby.moves = [];
        lobby.turn = 0;
        lobby.state = initState(lobby.game);
        lobby.t = nowSeq();
        await this.storage.put("l:" + code, lobby);
        return png(1, 1);
      }


      // ── Durak (authoritative dealer, 2 players) ────────────────────────────
      // Separate route set from the 2-int move/poll games: the worker OWNS the deck,
      // hands and seed, deals PRIVATELY per seat via /api/ddraw, and relays PUBLIC events
      // via an indexed /api/dlog. Clients rebuild table/trump/turn/roles/counts from the
      // public log and learn only their OWN card identities privately. All actions require
      // a seat token (tok → seat), which also gates ddraw so a cheat can't read a foreign
      // seat's private cards. Only 2 players are wired for now (3–4 seating is deferred).
      if (p === "/api/room") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return png(9, 1);                        // gone
        const started = lobby.state && lobby.state.started ? 2 : 1; // h: 2 started, 1 waiting
        return png(lobby.players, started);
      }
      if (p === "/api/start") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return png(9, 9);
        const seat = seatOf(lobby, q.get("tok"));
        if (seat < 0) return png(9, 3);
        const r = durakStart(lobby, seat);
        if (!r.ok) return png(9, r.code);
        await this.storage.put("l:" + code, lobby);
        return png(1, 1);
      }
      if (p === "/api/dact") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return png(9, 9);
        const seat = seatOf(lobby, q.get("tok"));
        if (seat < 0) return png(9, 3);
        const a = clampInt(q.get("a"), 0, 1, 4);
        const pr = clampInt(q.get("p"), 0, 0, 5);
        const c = clampInt(q.get("c"), 0, 0, 35);
        const r = durakAct(lobby, seat, a, pr, c);
        if (!r.ok) return png(9, r.code);
        await this.storage.put("l:" + code, lobby);
        return png(1, 1);
      }
      if (p === "/api/dlog") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return png(9, 9);
        const since = clampInt(q.get("since"), 0, 0, 100000);
        const ev = lobby.state && lobby.state.pub ? lobby.state.pub[since] : null;
        if (!ev) return png(1, 1);                           // nothing new (no event is (1,1))
        return png(ev.w, ev.h);
      }
      if (p === "/api/ddraw") {
        const lobby = code ? await this.storage.get("l:" + code) : null;
        if (!lobby) return png(9, 9);
        const seat = seatOf(lobby, q.get("tok"));
        if (seat < 0) return png(9, 3);                      // only your own seat's private cards
        const i = clampInt(q.get("i"), 0, 0, 100000);
        const priv = lobby.state && lobby.state.priv ? lobby.state.priv[seat] : null;
        const card = priv ? priv[i] : undefined;
        if (card === undefined || card === null) return png(1, 1); // no card at that index yet
        return png(card + 2, 1);
      }

      return png(9, 8); // unknown route
    } catch (e) {
      return png(9, 7); // server error marker
    }
  }

  async freshCode() {
    // 4-digit lobby code (1000..9999). Never return a code that's already taken — random
    // probes first, then a full linear scan as a fallback so we can't clobber a live lobby.
    for (let i = 0; i < 200; i++) {
      const c = 1000 + Math.floor(Math.random() * 9000);
      const existing = await this.storage.get("l:" + c);
      if (!existing) return c;
    }
    for (let c = 1000; c <= 9999; c++) {
      const existing = await this.storage.get("l:" + c);
      if (!existing) return c;
    }
    return 0; // server full (extremely unlikely); the client-side create just looks broken
  }


  // Opportunistic cleanup so a public relay's storage stays bounded. Runs at most
  // once a minute (guarded by a stored timestamp) and only off write paths
  // (create/quick), never on the hot poll loop. Drops lobbies idle for > 30 min.
  async maybeSweep() {
    const now = Date.now();
    const last = (await this.storage.get("lastSweep")) || 0;
    if (now - last < 60000) return;
    await this.storage.put("lastSweep", now);
    const all = await this.storage.list({ prefix: "l:" });
    for (const [key, lobby] of all) {
      if (lobby && lobby.t && now - lobby.t > 30 * 60000) {
        await this.storage.delete(key);
      }
    }
  }
}

function clampInt(v, dflt, lo, hi) {
  const n = parseInt(v, 10);
  if (isNaN(n)) return dflt;
  return Math.max(lo, Math.min(hi, n));
}

// A seat token must be a non-empty, sanely-bounded alphanumeric string. Rejecting junk /
// empty tokens stops us from ever creating an unusable "occupied but tokenless" seat (a
// seat whose empty tok makes seatOf return -1 forever), and the length cap keeps a caller
// from bloating Durable Object storage with a giant token. The client mint is 48 hex-ish
// chars (see MG.Session.newToken), comfortably inside these bounds.
function validTok(tok) {
  return typeof tok === "string" && tok.length >= 8 && tok.length <= 64 && /^[a-z0-9]+$/i.test(tok);
}

// Game ids the server is authoritative for. 3 = durak (its own route set). An id outside
// this set has no engine, so create/quick reject it up front and move never relays it.
const SUPPORTED_GAMES = { 1: 1, 2: 1, 3: 1, 4: 1, 5: 1 };


function nowSeq() {
  // Monotonic-ish tag for debugging; not used for logic.
  return Date.now();
}

/* ───────────────── authoritative identity + move validation ─────────────────
 * The seat token is the trust anchor. It flows ONLY upward (query param), is never
 * echoed in a response, and is long + random, so an observer can neither read nor
 * guess it. seatOf maps a presented token to its seat index (0/1) or -1 (→ (9,3)).
 * Fixed seat↔side mapping (matches the client): seat 0 = host, moves first.
 */
function rules() { return (typeof globalThis !== "undefined" && globalThis.MGRules) || {}; }

function seatOf(lobby, tok) {
  if (!tok || !lobby.seats) return -1;
  for (let i = 0; i < lobby.seats.length; i++) {
    const s = lobby.seats[i];
    if (s && s.tok && s.tok === tok) return i;
  }
  return -1;
}

// Fresh authoritative state per game. null = no server engine → legacy relay.
function initState(game) {
  const R = rules();
  if (game === 1) return { board: R.checkers.initialBoard(), chainSq: -1 }; // checkers
  if (game === 2) return { board: [0, 0, 0, 0, 0, 0, 0, 0, 0] };            // tic-tac-toe
  if (game === 4) return { board: R.chess.initialChessBoard(), cst: R.chess.initialChessState() }; // chess
  if (game === 3) return { started: 0, pub: [], priv: [[], []] };                                  // durak (dealt on /api/start)
  if (game === 5) return { board: R.connectfour.initialBoard() };                                  // connect four
  return null;
}

// Validate a move by the seat holder against the authoritative state. Returns
// { ok:true, move:{f,t,e} } (e computed by the SERVER) or { ok:false, code } where
// code is 1 (not your turn) or 2 (illegal move). Mutates lobby.state / lobby.turn on
// acceptance. A game with no server engine relays unchecked (backward compatible).
function validateMove(lobby, seat, from, to, end) {
  const R = rules();
  // No authoritative engine for this lobby → REJECT. We never blindly relay an unchecked
  // move (that would make the server a dumb, cheatable relay for any unknown game id).
  if (!lobby.state) return { ok: false, code: 2 };
  if (lobby.game === 1) return validateCheckers(R.checkers, lobby, seat, from, to);
  if (lobby.game === 2) return validateTtt(lobby, seat, from, to);
  if (lobby.game === 4) return validateChess(R.chess, lobby, seat, from, to);
  if (lobby.game === 5) return validateConnectFour(R.connectfour, lobby, seat, from, to);
  return { ok: false, code: 2 };
}


function validateCheckers(RC, lobby, seat, from, to) {
  const st = lobby.state, b = st.board;
  const side = seat === 0 ? RC.WHITE : RC.BLACK;
  const chaining = st.chainSq >= 0;
  // Turn: mid-chain only the chaining seat may move, and only its chain piece.
  if (chaining) { if (seat !== lobby.turn || from !== st.chainSq) return { ok: false, code: 1 }; }
  else if (seat !== lobby.turn) return { ok: false, code: 1 };
  if (RC.colorOf(b[from]) !== side) return { ok: false, code: 2 };
  // Legal targets for THIS piece, honouring forced capture / an active chain.
  let targets;
  if (chaining || RC.anyCaptureFor(b, side)) targets = RC.captureMoves(b, from);
  else targets = RC.simpleMoves(b, from);
  let ok = false;
  for (let i = 0; i < targets.length; i++) if (targets[i].to === to) { ok = true; break; }
  if (!ok) return { ok: false, code: 2 };
  const res = RC.applyHop(b, from, to); // mutates the authoritative board
  // Same piece may keep jumping (a capture, and not just crowned) → chain continues.
  const more = res.captured && !res.promoted && RC.captureMoves(b, to).length > 0;
  let e;
  if (more) { st.chainSq = to; e = 0; }                       // turn stays with this seat
  else { st.chainSq = -1; e = 1; lobby.turn = seat === 0 ? 1 : 0; } // hand off
  return { ok: true, move: { f: from, t: to, e: e } };
}

function validateTtt(lobby, seat, from, to) {
  const R = rules();
  const b = lobby.state.board;
  if (seat !== lobby.turn) return { ok: false, code: 1 };
  // Reject any move once the game is already decided (a win line or a full board), so a
  // loser can't keep placing marks and corrupt the finished log.
  if (R.ttt.tttWinner(b) || R.ttt.tttFull(b)) return { ok: false, code: 2 };
  // A placement is cell 0..8 with the fixed marker to===9, onto an empty cell.
  if (to !== 9 || from < 0 || from > 8 || b[from] !== 0) return { ok: false, code: 2 };

  b[from] = seat === 0 ? 1 : 2;              // X (host) / O (joiner)
  lobby.turn = seat === 0 ? 1 : 0;
  return { ok: true, move: { f: from, t: 9, e: 1 } };
}

function validateChess(RX, lobby, seat, from, to) {
  const st = lobby.state;
  const side = seat === 0 ? 1 : -1;          // white / black
  if (seat !== lobby.turn) return { ok: false, code: 1 };
  if (RX.cSign(st.board[from]) !== side) return { ok: false, code: 2 };
  const legal = RX.legalMoves(st.board, st.cst, side); // includes self-check filter, castling, ep
  let ok = false;
  for (let i = 0; i < legal.length; i++) if (legal[i].from === from && legal[i].to === to) { ok = true; break; }
  if (!ok) return { ok: false, code: 2 };
  const r = RX.makeMove(st.board, st.cst, from, to);
  st.board = r[0]; st.cst = r[1];
  lobby.turn = seat === 0 ? 1 : 0;           // every chess move ends the turn
  return { ok: true, move: { f: from, t: to, e: 1 } };
}

// Connect Four: a move is a COLUMN in `from` (0..6) with the fixed marker `to === 7` (so
// from != to always holds, exactly like tic-tac-toe's to === 9). The server derives the
// landing row via gravity and rejects a full column. Host = seat 0 = red, moves first.
function validateConnectFour(RC, lobby, seat, from, to) {
  const st = lobby.state;
  if (seat !== lobby.turn) return { ok: false, code: 1 };
  if (RC.winner(st.board) || RC.isFull(st.board)) return { ok: false, code: 2 }; // game already over
  if (to !== 7 || from < 0 || from >= RC.COLS) return { ok: false, code: 2 };

  const r = RC.drop(st.board, from, seat === 0 ? 1 : 2);
  if (!r) return { ok: false, code: 2 };     // column full
  st.board = r.board;
  lobby.turn = seat === 0 ? 1 : 0;
  return { ok: true, move: { f: from, t: 7, e: 1 } };
}

/* ───────────────────── Durak authoritative dealer (2 players) ─────────────────────
 * Public event encoding (each fits the 2-int downlink, both dims <= ~63; NONE is (1,1)):
 *   TRUMP        (2,  trumpCard+1)
 *   OPEN atk a   (3,  a+1)                     first attacker seat
 *   PLAY  s c    (10+s, c+1)                   seat s attacks/throws in card c
 *   COVER p c    (20+p, c+1)                   defender covers table pair p with card c
 *   TAKE  s      (30+s, 1)                     seat s (defender) takes the table
 *   BITO         (40,   1)                     table beaten & discarded
 *   DRAW  s n    (50+s, n+1)                   seat s drew n cards from the deck
 *   OVER  L      (60,   L+2)                   game over; L = fool seat (-1 = draw)
 * Private per-seat draws go to state.priv[seat] and are pulled one index at a time via
 * /api/ddraw (gated by the seat token), encoded as (card+2, 1). The +2 is deliberate:
 * card id 0 would otherwise collide with the universal (1,1) "nothing new" marker.
 */
function dpush(st, w, h) { st.pub.push({ w: w, h: h }); }

function durakStart(lobby, seat) {
  const R = rules().durak;
  const st = lobby.state;
  if (!st || st.started) return { ok: true };            // idempotent (already dealt)
  if (seat !== 0) return { ok: false, code: 1 };         // only the host (seat 0) starts
  if (lobby.players < 2) return { ok: false, code: 2 };  // need both players
  const seedBuf = new Uint32Array(1); crypto.getRandomValues(seedBuf);
  const seed = seedBuf[0] & 0x7fffffff;                  // SERVER owns the seed (never sent down)
  const g = R.newGame(2, seed);

  st.numPlayers = 2;
  st.trump = g.trump; st.trumpCard = g.trumpCard;
  st.deck = g.deck; st.hands = g.hands; st.table = g.table;
  st.attacker = g.attacker; st.defender = g.defender; st.phase = g.phase;
  st.discard = g.discard; st.out = g.out; st.loser = g.loser;
  st.pub = []; st.priv = [[], []];
  st.started = 1;
  dpush(st, 2, g.trumpCard + 1);                         // TRUMP
  dpush(st, 3, g.attacker + 1);                          // OPEN(first attacker)
  for (let s = 0; s < 2; s++) {
    for (let k = 0; k < g.hands[s].length; k++) st.priv[s].push(g.hands[s][k]);
    dpush(st, 50 + s, g.hands[s].length + 1);            // DRAW(s, 6)
  }
  return { ok: true };
}

// Resolve a bout, then emit DRAW events for the DECK cards each seat picked up during
// refill. A card drawn from the deck is one now in a hand that WAS in the pre-bout deck
// (hands and deck are disjoint before the bout), so hand_after ∩ deckBefore = the draws.
// Table cards a taker picks up were already public, so they are NOT re-emitted.
function durakEndBout(st, took) {
  const R = rules().durak;
  const before = {};
  for (let i = 0; i < st.deck.length; i++) before[st.deck[i]] = 1;
  R.endBout(st, took);
  for (let s = 0; s < st.numPlayers; s++) {
    const drawn = [];
    for (let k = 0; k < st.hands[s].length; k++) if (before[st.hands[s][k]]) drawn.push(st.hands[s][k]);
    if (drawn.length) {
      for (let d = 0; d < drawn.length; d++) st.priv[s].push(drawn[d]);
      dpush(st, 50 + s, drawn.length + 1);               // DRAW(s, n)
    }
  }
  if (st.phase === "over") dpush(st, 60, st.loser + 2);  // OVER(loser)
}

// Validate + apply one durak action by the seat holder. a: 1 attack, 2 cover, 3 take, 4 bito.
function durakAct(lobby, seat, a, p, c) {
  const R = rules().durak;
  const st = lobby.state;
  if (!st || !st.started || st.phase === "over") return { ok: false, code: 2 };
  if (a === 1) {                                         // attack / throw-in
    if (!R.canAttackWith(st, seat, c)) {
      // distinguish "not your role/turn" from "illegal card" for a friendlier client message
      if (seat === st.defender) return { ok: false, code: 1 };
      return { ok: false, code: 2 };
    }
    R.applyAttack(st, seat, c);
    dpush(st, 10 + seat, c + 1);
    return { ok: true };
  }
  if (a === 2) {                                         // cover a table pair
    if (seat !== st.defender) return { ok: false, code: 1 };
    if (!R.canDefendPair(st, p, c)) return { ok: false, code: 2 };
    R.applyDefend(st, p, c);
    dpush(st, 20 + p, c + 1);
    return { ok: true };
  }
  if (a === 3) {                                         // take
    if (seat !== st.defender) return { ok: false, code: 1 };
    if (st.table.length === 0) return { ok: false, code: 2 };
    dpush(st, 30 + seat, 1);
    durakEndBout(st, true);
    return { ok: true };
  }
  if (a === 4) {                                         // bito (beat)
    if (seat !== st.attacker) return { ok: false, code: 1 };
    if (st.table.length === 0 || R.uncoveredCount(st) !== 0) return { ok: false, code: 2 };
    dpush(st, 40, 1);
    durakEndBout(st, false);
    return { ok: true };
  }
  return { ok: false, code: 2 };
}


/* ─────────────────────────── PNG encoder ───────────────────────────
 * Emits an 8-bit grayscale PNG of exactly W x H black pixels. Data is all
 * zeros, wrapped in zlib "stored" (uncompressed) deflate blocks — no real
 * compression needed. The client only cares about the dimensions.
 */
function png(w, h) {
  w = Math.max(1, Math.min(w | 0, 8000));
  h = Math.max(1, Math.min(h | 0, 8000));

  const sig = [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a];
  const ihdr = u32(w).concat(u32(h), [8, 0, 0, 0, 0]); // 8-bit, grayscale

  // Raw scanlines: each row = 1 filter byte (0) + W pixel bytes (0). All zeros.
  const rawLen = h * (1 + w);

  // zlib stream: header + stored deflate blocks + adler32.
  const zlib = [0x78, 0x01];
  let off = 0;
  do {
    const blockLen = Math.min(65535, rawLen - off);
    const final = off + blockLen >= rawLen ? 1 : 0;
    zlib.push(final, blockLen & 255, (blockLen >> 8) & 255,
      ~blockLen & 255, (~blockLen >> 8) & 255);
    for (let i = 0; i < blockLen; i++) zlib.push(0);
    off += blockLen;
  } while (off < rawLen);
  zlib.push(...u32(adler32Zeros(rawLen)));

  const bytes = sig
    .concat(chunk("IHDR", ihdr))
    .concat(chunk("IDAT", zlib))
    .concat(chunk("IEND", []));

  return new Response(new Uint8Array(bytes), {
    headers: {
      "content-type": "image/png",
      "cache-control": "no-store, no-cache, must-revalidate, max-age=0",
      "access-control-allow-origin": "*",
    },
  });
}

function u32(n) {
  return [(n >>> 24) & 255, (n >>> 16) & 255, (n >>> 8) & 255, n & 255];
}

function chunk(type, data) {
  const t = [type.charCodeAt(0), type.charCodeAt(1), type.charCodeAt(2), type.charCodeAt(3)];
  const body = t.concat(data);
  return u32(data.length).concat(body, u32(crc32(body)));
}

// Adler32 of an all-zeros buffer of length n. a stays 1; b = (n * 1) mod 65521.
function adler32Zeros(n) {
  const MOD = 65521;
  const a = 1;
  const b = ((n % MOD) * 1) % MOD; // each step adds a(=1)
  return ((b << 16) | a) >>> 0;
}

let CRC_TABLE = null;
function crc32(bytes) {
  if (!CRC_TABLE) {
    CRC_TABLE = new Uint32Array(256);
    for (let n = 0; n < 256; n++) {
      let c = n;
      for (let k = 0; k < 8; k++) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
      CRC_TABLE[n] = c >>> 0;
    }
  }
  let crc = 0xffffffff;
  for (let i = 0; i < bytes.length; i++) {
    crc = CRC_TABLE[(crc ^ bytes[i]) & 255] ^ (crc >>> 8);
  }
  return (crc ^ 0xffffffff) >>> 0;
}
